### ISSUE TITLE
Add cache control header to Publication REST endpoint

### ISSUE THREAD

**Issue by Yalz** [Informatievlaanderen/VSDS-LDESServer4J#100]
### Problem
In our current implementation of the fragmentation, we assign a immutable header to a LDES Fragment.
However this is now not returned in the Publication REST endpoint. 
Together with the immutable header, we should also be able to mention how long a mutable fragment is allowed to be cached

### Suggestion

Add cache control header to Publication REST endpoint

**Comment by WLefever-Cegeka** [comment]
Thanks, @Yalz. This was implemented in #103.
