### ISSUE TITLE
Suggestions on LDES Server Docs

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#1008]
**This case is made to list all points of doc that need to improved:** 
---

- https://informatievlaanderen.github.io/VSDS-LDESServer4J/ => Increase the resolution of the Image at bottom? I feel it is too blurred.
- --
- https://informatievlaanderen.github.io/VSDS-LDESServer4J/how-to-run.html 
    - Put the sample configuration first then introduce which are the optional configurations? Like this is easier to start 
    - The configuration table with a better format? Thicker column lines? Now it is difficult to see there is a line in between ..
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/4f485333-a5b0-441a-a803-c595eb4f79ce)
    - A empty column after default value? 
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/c18dd987-c5c1-46f1-af1c-b51e7e3a1330)
---
- https://informatievlaanderen.github.io/VSDS-LDESServer4J/configuration/event-stream
   - To **house** (host?) a new Event Stream on your server, [typo]
   - SHACL (Shapes Constraint Language) (A link to SHACL ? https://www.w3.org/TR/shacl/)
---
- https://informatievlaanderen.github.io/VSDS-LDESServer4J/configuration/dcat
    -Example of a DCAT ?

**Comment by jobulcke** [comment]
This effort has been done, so this issue will be closed
