### ISSUE TITLE
View config should not be able to contain multiple retention policies of the same type (e.g. timebased or versionbased).

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-LDESServer4J#1009]
See title:
View config should not be able to contain multiple retention policies of the same type (e.g. timebased or versionbased).

When a user tries this, we should block it and return a clear error message.

**Comment by jeflaenen** [comment]
Jira ticket https://vlaamseoverheid.atlassian.net/browse/VSDSPUB-1104 is created for this.
