### ISSUE TITLE
Eventstream/View should not be created when retention module throws and exception

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-LDESServer4J#1010]
**Describe the bug**
When you create an eventstream or view with an invalid retention policy, you get a 400 http response with an error message. However the eventstream is still created in the database. It is no long possible to now create the valid eventstream because it will already exist without a retention policy on its view.

This is a problem because we cannot modify views, then we have to go and delete the view and recreate it. 

**To Reproduce**
1. Create an eventstream or view with an invalid retention policy
2. Observe the error you get
3. Send the same request to the server
4. Observe how you get a duplicate eventstream/view response..

**Expected behavior**
The state of the server is not changed when the request for a new eventstream/view is rejected.

**Comment by jeflaenen** [comment]
Jira ticket https://vlaamseoverheid.atlassian.net/browse/VSDSPUB-1104 is created for this.
