### ISSUE TITLE
Push autoincrement down to mongo

### ISSUE THREAD

**Issue by sandervd** [Informatievlaanderen/VSDS-LDESServer4J#1015]
**Is your feature request related to a problem? Please describe.**
https://github.com/Informatievlaanderen/VSDS-LDESServer4J/blob/f1d30f95a02be8cd03ff9a7defcced583e6cd4ca/ldes-server-infra-mongo/mongo-ingest-repository/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/ingest/membersequence/IngestMemberSequenceService.java
Determining the sequence requires a round-trip to the db.

**Describe the solution you'd like**
This can be avoided by making the increment procedure a function on the db:
https://www.mongodb.com/docs/v2.2/tutorial/create-an-auto-incrementing-field/

**Comment by Yalz** [comment]
Deprecated since 3.x no longer uses mongo
