### ISSUE TITLE
Retrieving a view is very slow and possibly even times out on fetch

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-LDESServer4J#1028]
**Describe the bug**
When a LDES contains a large(r) number of members than retrieving the view takes a (very) long time. This is due to the `remainingItems` being calculated.

**To Reproduce**
Try to fetch view http://brugge.ldes.geomobility.eu/observations/by-page 
This returns a 504 Gateway Time-out

**Expected behavior**
View is displayed in a timely manner.

**Comment by jobulcke** [comment]
This may be moved to Jira (if we still wants to add remaing members after it has been disabled for 4-5 months now) and/or needs to be re-evaluated after the Postgres migration, as the count query there should faster than in Mongo

**Comment by jobulcke** [comment]
No longer relevant
