### ISSUE TITLE
Actuator uses LDES server internal URLs

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-LDESServer4J#1029]
**Describe the bug**
When a LDES server is deployed behind a API gateway, the actuator uses the internal, private base URLs.

**To Reproduce**
Fetch https://telraam-api.net/ldes/actuator
Note that the internal addresses are being used.
Navigating to one of these links obviously does not work.

**Expected behavior**
The actuator uses the external addresses. The base address is configured in the `host-name`.

**Comment by jobulcke** [comment]
Resolved in https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pull/1246
