### ISSUE TITLE
Performance improvement: retention and ingest in 1 go

### ISSUE THREAD

**Issue by sandervd** [Informatievlaanderen/VSDS-LDESServer4J#1036]
**Is your feature request related to a problem? Please describe.**
Each ingested member requires multiple roundtrips to the database. This has a big impact on the throughput.

**Describe the solution you'd like**
To maintain the same elegance of domain separation, a synchronous event could be used, allowing the retention module to add to the object that is about to be stored in the database (microkernel architecture) by the fetching module. This would remove the need for separate collections.

**Describe alternatives you've considered**
Keep the situation as-is.

**Additional context**
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/1673560/2429b013-8a90-4b73-96be-c4fe42fdaa50)

**Comment by sandervd** [comment]
In #1015 another ingest performance issue is reported.

**Comment by Tomvbe** [comment]
Let's discuss this

**Comment by Yalz** [comment]
After discussion, we don't think this is worth the investment:

- Ingestion & Retention are now not only two responsabilities but also jobs
- Implementing this might harm ingestion perfo
- This is a solution for an edge case. You normally don't expect to ingest members that immetiately will be deprecated
