### ISSUE TITLE
Add use-relative-url to LDES Server doc

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#1056]
### Discussed in https://github.com/Informatievlaanderen/VSDS-LDESServer4J/discussions/1050

<div type='discussions-op-text'>

<sup>Originally posted by **xdxxxdx** December 12, 2023</sup>
Thanks to feature, https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/5c2d6975c616d61576248fdead7b2a7f75d65dfa
which key is used for enabling it ? Thanks

I guess: ldes-server.use-relative-url?</div>

Please add new setting: use-relative-url to the doc, thanks

**Comment by pj-cegeka** [comment]
ldes-server.use-relative-url is indeed the correct property. the documentation has been updated to contain a more detailed explanation.
