### ISSUE TITLE
Follow up story/gh issue: fetch all fragments with one query and map the sizes to the fragments.

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-LDESServer4J#1060]
**Follow up on:**
https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pull/1059/files#diff-a3148ba428094046d807206f630e64cd3d8d46938349f871fa1868f4210b12ea

**Refer to:** ldes-server-compaction/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/compaction/application/services/CompactionCandidateService.java

**Method:**
private List<CompactionCandidate> getPossibleCompactionCandidates(ViewCapacity viewCapacity)

**Action:**
Fetch all fragments with one query and map the sizes to the fragments. Maybe immediately add the filters below to the query.

**Comment by jobulcke** [comment]
Resolved with the migration to Postgres and Spring Batch
