### ISSUE TITLE
Performance improvement: Bulk member allocation

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-LDESServer4J#1063]
From compaction PR: https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pull/1059/files/8bd1f36689fd316b3fd9ed9b9757ed894c745786#diff-b1774d68e0ea189215e11e16e581ccea2437a571b01c4838a8b7078c1f1cff52

The compaction flow currently assigns members to a newly created fragment and will then loop over all the individual members and send MemberAllocatedEvents which all result in individual database queries. We should look into having a BulkMemberAllocatedEvent object to make it possible to assign all these members to a new fragment in one action.

**Comment by Yalz** [comment]
Fixed in #1059
