### ISSUE TITLE
docker-compose up  on docker-compose.yml doesn't start containers.

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#1104]
Follow: https://github.com/Informatievlaanderen/VSDS-LDESServer4J?tab=readme-ov-file#docker-setup
Run: 
```
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
docker-compose up
```
on https://github.com/Informatievlaanderen/VSDS-LDESServer4J/blob/main/docker-compose.yml

Related containers doesn't start. 
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/04f27b31-f067-476d-acad-0e1cc36a98ee)

With the change of https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/1da09b0040f7ca665c26c15f4aef5e221a720c7b

There is no local build of ldes-server.
I am not sure about: https://github.com/Informatievlaanderen/VSDS-LDESServer4J/blob/265bf1fe6614203d01f69c8a00d46601e7d67610/docker-compose.yml#L20

Thanks

**Comment by Yalz** [comment]
Was indeed an oversight. Is corrected now
