### ISSUE TITLE
When ingesting the data without a proper tree:fragmentationPath triple inside, a proper error should be displayed

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#1105]
**_Version:_** [ldes/ldes-server: 2.7.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldes-server/tags)

**Prerequisites：**
1. Stream is configured with: 
```@prefix ldes:    <https://w3id.org/ldes#> .
@prefix tree:    <https://w3id.org/tree#>.
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix prov:    <http://www.w3.org/ns/prov#> .
@prefix sh:      <http://www.w3.org/ns/shacl#> .

</nodes> a ldes:EventStream ;
  tree:shape [ a sh:NodeShape ] ;
  ldes:timestampPath prov:generatedAtTime ;
  ldes:versionOfPath dcterms:isVersionOf .
```

2. View is configured with:
```
@prefix tree:   <https://w3id.org/tree#>.
@prefix xsd:    <http://www.w3.org/2001/XMLSchema#> .
@prefix ldes:   <https://w3id.org/ldes#> .
@prefix prov:   <http://www.w3.org/ns/prov#> .

</nodes/paged> a tree:Node ;
  tree:viewDescription [
    a tree:ViewDescription ;
    tree:fragmentationStrategy  ([
      a tree:HierarchicalTimeBasedFragmentation ;
      tree:memberLimit "10"^^xsd:integer ;
      tree:maxGranularity "day" ;
      tree:fragmentationPath prov:generatedAtTime ;
    ]) ;
    ldes:retentionPolicy [
      a ldes:LatestVersionSubset ;
      ldes:amount 1 ;
    ] ;
    tree:pageSize "10"^^<http://www.w3.org/2001/XMLSchema#int> ;
] .
```
**Scenario:**
Post 
```
@prefix ns0: <https://vocabulary.uncefact.org/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix dc: <http://purl.org/dc/terms/> .
@prefix ns1: <https://schema.org/> .

<https://vocabulary.uncefact.org/servicingSpecifiedParty1>
  a <https://vocabulary.uncefact.org/LocationParty> ;
  ns0:name "DP-World"^^xsd:string .

<node:84>
  a ns0:LogisticsLocation ;
  dc:isVersionOf <node:323> ;
  ns1:latitude 5.236760e+1 ;
  ns1:longitude 4.904100e+0 ;
  ns0:name "k1700"^^xsd:string ;
  ns0:servicingSpecifiedParty ns0:servicingSpecifiedParty1 .
```
To stream.

**Current result:**
As there is no `prov:generatedAtTime` inside the data
The member has been ingested to database => Right
The member is not linked to the fragment => Right

In the Server log we can see:
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/02b036eb-5c71-4b8e-93b6-560ede0e3035)

I think it is better to have a error log
e,g, ` Triple of configured fragmentationPath is missing in the ingested data`

Full log: 

[2024-01-17 152154 2024-01-17T142154.txt](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/13964848/2024-01-17.152154.2024-01-17T142154.txt)

**Comment by Yalz** [comment]
Hi @xdxxxdx ,
This should be covered by introducing a default bucket for fragmentations. This will be picked up soon.

**Comment by pj-cegeka** [comment]
An error is no longer throw in cases like this, now the member will be placed in the default bucket of the view.
