### ISSUE TITLE
Warning message:  `Duplicate member ingested. Member with id xx already exist` missing

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#1109]
**Prerequisites:**
1. Docker image version: [Snapshot 2.7.0](https://hub.docker.com/layers/ldes/ldes-server/2.7.0-SNAPSHOT/images/sha256-6e601ebd4c799070ca897dd1f0c09c4a619617792fc2e74304deaa3af5876b84?context=explore)
2. The view nodes are configured on the server by posting the following configuration:
```
@prefix ldes: <https://w3id.org/ldes#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix tree: <https://w3id.org/tree#>.
@prefix sh:   <http://www.w3.org/ns/shacl#> .
@prefix server: <http://localhost:8080/> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
@prefix nodes: <http://localhost:8080/nodes/> .

server:nodes a ldes:EventStream ;
	ldes:timestampPath dcterms:created ;
	ldes:versionOfPath dcterms:isVersionOf ;
	tree:shape nodes:shape .

nodes:shape a sh:NodeShape ;
	sh:targetClass <https://vocabulary.uncefact.org/LogisticsLocation> 
```
3. Configure a pagination view by post 
```
@prefix tree:   <https://w3id.org/tree#>.
@prefix xsd:    <http://www.w3.org/2001/XMLSchema#> .
@prefix ldes:   <https://w3id.org/ldes#> .
@prefix prov:   <http://www.w3.org/ns/prov#> .

</nodes/paged> a tree:Node ;
  tree:viewDescription [
    a tree:ViewDescription ;
    tree:fragmentationStrategy  () ;
    ldes:retentionPolicy [
      a ldes:LatestVersionSubset ;
      ldes:amount 1 ;
    ] ;
    tree:pageSize "10"^^<http://www.w3.org/2001/XMLSchema#int> ;
] .
```
**Scenarios**
1. Post the following member to the `nodes` stream
```
@prefix dc: <http://purl.org/dc/terms/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix ns0: <https://schema.org/> .
@prefix ns1: <https://vocabulary.uncefact.org/> .

<http://example.org/node/id/1/2>
  a <https://vocabulary.uncefact.org/LogisticsLocation> ;
  dc:isVersionOf "http://example.org/node/id/1"^^xsd:string ;
  prov:generatedAtTime "2021-05-20T10:00:00Z"^^xsd:dateTime ;
  ns0:latitude 5.236760e+1 ;
  ns0:longitude 4.904100e+0 ;
  ns1:name "k1700"^^xsd:string ;
  ns1:servicingSpecifiedParty ns1:servicingSpecifiedParty1 .

ns1:servicingSpecifiedParty1
  a ns1:LocationParty ;
  ns1:name "DP-World"^^xsd:string .
```
2. The entity <http://example.org/node/id/1/2> is added to the nodes stream
3. Post again the member with the same identity <http://example.org/node/id/1/2>
```
@prefix dc: <http://purl.org/dc/terms/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix ns0: <https://schema.org/> .
@prefix ns1: <https://vocabulary.uncefact.org/> .

<http://example.org/node/id/1/2>
  a <https://vocabulary.uncefact.org/LogisticsLocation> ;
  dc:isVersionOf "http://example.org/node/id/1"^^xsd:string ;
  prov:generatedAtTime "2021-05-20T10:00:00Z"^^xsd:dateTime ;
  ns0:latitude 5.236760e+1 ;
  ns0:longitude 4.904100e+0 ;
  ns1:name "k1700"^^xsd:string ;
  ns1:servicingSpecifiedParty ns1:servicingSpecifiedParty1 .

ns1:servicingSpecifiedParty1
  a ns1:LocationParty ;
  ns1:name "DPTEST-World"^^xsd:string . [MODIFIED]
```
**Current behavior**
The modified member with the same entity has not been ingested to the stream and there is no warning message displayed in the server log.
I tried with version  [Snapshot 2.4.0](https://hub.docker.com/layers/ldes/ldes-server/2.4.0-SNAPSHOT/images/sha256-6e601ebd4c799070ca897dd1f0c09c4a619617792fc2e74304deaa3af5876b84?context=explore)
There was log 
`2024-01-18 15:07:11 2024-01-18T14:07:11.885Z  WARN 1 --- [nio-8080-exec-5] b.v.i.l.s.ingest.MemberIngesterImpl      : Duplicate member ingested. Member with id nodes/http://example.org/node/id/1/2 already exist
`
Full log for snapshot 2.4.0: 
[2024-01-18 150635-Snapshot2.4.0 .txt](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/13977648/2024-01-18.150635-Snapshot2.4.0.txt)
I think it is better to keep this warning log, as the member change is not saved to the stream.
Thanks

**Comment by pj-cegeka** [comment]
We have reenabled this warning, this change will be active in the next release.
We have also changed the returned status code on the ingest endpoint. A normally ingested member will return 201 while a duplicate member will return 200. These changes will be explained in the updated documentation
