### ISSUE TITLE
Add a section in the doc about APIs.

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#1131]
Add a section in the doc: https://informatievlaanderen.github.io/VSDS-LDESServer4J/ 
to explain the Admin/Management API ( e,g, tp://localhost:8080/v1/swagger-ui/index.html). Maybe embedded this swagger API to the document webpage.  Something like 
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/1db7d990-48cc-42cf-89db-8304abeb253f)

Thanks

**Comment by jobulcke** [comment]
Duplicate issue as #1163
