### ISSUE TITLE
Provide default shape when none is provided

### ISSUE THREAD

**Issue by Yalz** [Informatievlaanderen/VSDS-LDESServer4J#1135]
**Is your feature request related to a problem? Please describe.**
Before the homogenous stream, the SHACL shape was amandatory to mention the targetClass to indicate the type of the stream.
However, this is no longer necessary. Since a stream can contain multiple types.

**Describe the solution you'd like**
If no shape is provided, create a empty shape for it.

**Describe alternatives you've considered**
Leave this resposability with the Event Stream creator, but this is a unnecessary effort.

**Comment by pj-cegeka** [comment]
When no shape is present, the SHACL validation is simply skipped now.
