### ISSUE TITLE
[clean code] ModelParser.class should be moved out of fragmentisers-common

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-LDESServer4J#1152]
This is a 'generic' class with static methods that is used by TimeBased and Geospatial fragmentation but both fragmentation strategies have one public method that they use and no shared logic. It does not make sense to have this a shared class. This logic can be moved to the bucketizers of these fragmentation strategies as seen in ReferenceBucketiser

**Comment by jobulcke** [comment]
Resolved in #1247
