### ISSUE TITLE
Generate and provide swagger as actual admin api documentation

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-LDESServer4J#1163]
We are already using swagger to completely document the admin api but this documentation is not used as actual documentation for people getting to know the server. They see parts of it in the documentation but having a clear and up to date swagger page would be a lot more helpful.

This would be in the following interactive format: https://petstore.swagger.io/

We could automate this to prevent adding manual tasks of re-generating this on releases. Suggestion: https://github.com/peter-evans/swagger-github-pages

**Comment by Yalz** [comment]
https://app.swaggerhub.com/search
