### ISSUE TITLE
Compaction job throws exception on server without data

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-LDESServer4J#1178]
I noticed this on the server in the load testing environment on a night that there was no data:

![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/34196062/d3e01efe-9648-4c39-a22b-609a8c04bd23)

I would expect no errors in this case

**Comment by jobulcke** [comment]
resolved in #1238
