### ISSUE TITLE
Doc: max-age or maxage? for catching headers.

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#1185]
In the documentation, https://github.com/Informatievlaanderen/VSDS-LDESServer4J/blob/ad690159a74d6f1aec38e9a8e4d80ffb6c638b75/docs/how-to-run.md?plain=1#L93
`rest. max-age` is used as a configuration key for mutable caching headers.
But In the example of configurations, which is `maxage` https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/fd048adf61350e70344ae976050810effde0939e/tests/019.server-supports-cacheability/config/ldes-server.config.yml#L18C3-L18C9

p.s. max-age is not working if set to `ldes-server.config`, I think the doc should be changed accordingly.
Thanks

**Comment by Yalz** [comment]
Hi @xdxxxdx , 
It's true that it can be confusing between the different casing types.
However, camelCase, kebab-case and snake_case. can be used interchangeably in spring configuration. So both are correct
