### ISSUE TITLE
[Spec]: `tree:InBetweenRelation` should not be used as current way in time based fragmentations.

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#1186]
[Spec]: `tree:InBetweenRelation` should not be used as the current way in time-based fragmentations.
```
@prefix prov:  <http://www.w3.org/ns/prov#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix terms: <http://purl.org/dc/terms/> .
@prefix tree:  <https://w3id.org/tree#> .

<../../bearb/timebased?year=2015>
        rdf:type        tree:Node;
        terms:isPartOf  <../../bearb>;
        tree:relation   [ rdf:type    tree:InBetweenRelation;
                          tree:node   <../../bearb/timebased?year=2015&month=08>;
                          tree:path   prov:generatedAtTime;
                          tree:value  "2015-08"^^<http://www.w3.org/2001/XMLSchema#gYearMonth>
                        ] .
```
This has been discussed since the very beginning of this usage. 
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/4c136687-0782-4c6d-8304-a49a788d39f3)
@pietercolpaert addressed concern on this. https://github.com/TREEcg/specification/issues/82#issuecomment-1709605508 
https://vsdscore.slack.com/archives/C03CQKA4RU7/p1691138145204079

Thanks

**Comment by Yalz** [comment]
AP: To replace with GreaterThanOrEquals and LesserThan relations pointing to each fragment
