### ISSUE TITLE
Deleting a view should not result in deleting members

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-LDESServer4J#1208]
Currently, if you delete the last view of a LDES all existing members are also deleted. This is **unexpected behavior** as the data publisher is unaware of this behavior. Note that it is perfectly possible to have a LDES with members without a view: you just need to create a LDES and ingest data without creating a view therefore there is no reason why members should be deleted upon deleting the last view of a LDES.

The only time a member should be deleted is if according to all retention policies (defined on a view) of the LDES it should not be retained. Note that if one view of a LDES does not have a retention policy this means that members of that LDES are **never** deleted. In fact, the retention background checks for that LDES can be omitted in that case.

**Comment by Yalz** [comment]
VSDSPUB-1239

**Comment by Yalz** [comment]
Story effort is done under scope of "Event Source" feature
