### ISSUE TITLE
Return Shacl report when versionOf predicate is present in state object on ingest

### ISSUE THREAD

**Issue by sandervd** [Informatievlaanderen/VSDS-LDESServer4J#1218]
**Is your feature request related to a problem? Please describe.**
It would be consistent to always reply with a shacl report for api errors

**Describe the solution you'd like**
SHACL report

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by pj-cegeka** [comment]
All ingest validation errors are now bundled in a SHACL report
