### ISSUE TITLE
Inline SHACL validation on ingest as Java code

### ISSUE THREAD

**Issue by sandervd** [Informatievlaanderen/VSDS-LDESServer4J#1229]
**Describe the bug**
Perfo of ingest is negatively impacted by my wonky dangling bnode detection SHACL file. 

**To Reproduce**
1. Run the server with Pyroscope tracing enabled
2. Ingest some data
3. Inspect the profile

**Expected behavior**
Less cpu cycles spend on the validation.
Inlining the logic in Java will do the trick.

**Screenshots**
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/1673560/d572a2f0-f680-417f-b8e0-f1cc1e2d1a93)

**Comment by pj-cegeka** [comment]
Is implemented by https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pull/1237
