### ISSUE TITLE
Store protobuf in the db

### ISSUE THREAD

**Issue by sandervd** [Informatievlaanderen/VSDS-LDESServer4J#1236]
**Is your feature request related to a problem? Please describe.**
A lot of time is spend in the app serializing an de-serializing to and from RDF text to in memory models.
By storing protobuf in the db, we could seriously cut down the overhead.

**Describe the solution you'd like**
Store protobuf instead of ntriples in the db.

**Comment by jobulcke** [comment]
What about configuring this as a spring property? Because maybe people want to be able to read the data in the db (this could be valuable especially in development) or wants to choose a smaller format (I don't know if binary data is a smaller format than turtle)

**Comment by sandervd** [comment]
If decoding data in the db is an issue, we could foresee a simple debug tool as a helper?
I agree that we might have to make this configurable, but in a first iteration  it would already be good to have a branch we can run the performance tests against. If it is worth the gain, we can then expand on it and make the config options?
