### ISSUE TITLE
Hulp Nodig link doesnt work.

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#1261]
https://informatievlaanderen.github.io/VSDS-LDESServer4J/
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/721796b2-5b11-4885-a49f-2a880f5a02b0)
There is no link option pop out after mouse over...

**Comment by Yalz** [comment]
To be replaced such as https://informatievlaanderen.github.io/VSDS-Tech-Docs/
