### ISSUE TITLE
Error that eventstream cannot be found is thrown when removing an eventstream

### ISSUE THREAD

**Issue by jeflaenen** [Informatievlaanderen/VSDS-LDESServer4J#1279]
**Describe the bug**
When trying to remove the eventstream "observations" through the admin API, an error is received that the eventstream could not be found.

![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/29032795/3e0647eb-2d44-4785-a65e-08ad1fdc066f)
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/29032795/9ee1050e-98b9-4d76-809b-77d3ce94ce80)

A curl to check the overview of evenstreams returns nothing:
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/29032795/f46eb942-c648-40b9-84b3-5a1f39d2d449)

**Expected behavior**
The evenstream is deleted and an error is only thrown when something actually goes wrong.

**Additional info**
Test was done on the load-testing environment.

**Comment by jobulcke** [comment]
Closing since inactive
