### ISSUE TITLE
Character encoding test

### ISSUE THREAD

**Issue by sandervd** [Informatievlaanderen/VSDS-LDESServer4J#1286]
**Is your feature request related to a problem? Please describe.**
To make sure that we don't encounter any character encoding issues, we should test.

**Describe the solution you'd like**
https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.json
Transform this json array to triples, and ingest them in the server. Validate that the output matches the input.

**Comment by Yalz** [comment]
Linked to #1288
