### ISSUE TITLE
Datetime not compliant with the ISO8601 format

### ISSUE THREAD

**Issue by ddvlanck** [Informatievlaanderen/VSDS-LDESServer4J#1295]
**Describe the bug**
When the fragmentation is configured to fragment down to the hourly level, you get relations with `tree:value`s like this `2023-05-28T18`, which is not a valid ISO8601 format.

**To Reproduce**
Found this error while trying to parse the Linked Data from the following fragment: https://brugge-ldes.geomobility.eu/observations/by-time?year=2023&month=05&day=28.

**Expected behavior**
I expect the timestamp to be in a correct ISO8601 format, which is `2023-05-28T18:00:00` for example.

**Comment by Yalz** [comment]
This is a non-issue. As the tree:value is a string value with no restrictions of type formats.
In the newer versions (keep in mind your server is about 7 months old), this is fixed with an actual xsd:datetime value where it does comply to the ISO standard.
