### ISSUE TITLE
Errors in OpenAPI spec

### ISSUE THREAD

**Issue by dewolfs** [Informatievlaanderen/VSDS-LDESServer4J#1299]
**Describe the solution you'd like**

The process at my customer mandates to imports APIs only using OpenAPI specification files.
A pre-validation linting task is executed.

[Spectral ](https://stoplight.io/open-source/spectral ) is used as tool to verify the state of the OpenAPI spec.
The Spectral OpenAPI ruleset: https://docs.stoplight.io/docs/spectral/4dec24461f3af-open-api-rules

When we run spectral against Ldes server v2.3.0, we get the following results:

**The results admin api:**

```
error  oas3-schema            Object must have required property "info".
error  path-params            Paths "/admin/api/eventstreams/{collectionName}/views/{viewName}" and "/admin/api/eventstreams/{collectionName}/views/{view}" must not be equivalent.
warning  operation-description  Operation "description" must be present and non-empty string
warning  operation-tag-defined  Operation tags must be defined in global tags.
```

**The results data api:**

```
error  oas3-schema            Object must have required property "info".
error  path-params            Paths "/{collectionName}" and "/{collectionname}" must not be equivalent.
warning  operation-description  Operation "description" must be present and non-empty string
warning  operation-tag-defined  Operation tags must be defined in global tags.
```

Can you look into fixing the errors so that the OpenAPI spec is compliant ?

**Comment by jobulcke** [comment]
Resolved in #1312
