### ISSUE TITLE
Event source api, body is required but no example

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#1302]
[ldes/ldes-server:3.0.0-SNAPSHOT](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#) is up and running
go to API endpoint: http://localhost:8080/v1/swagger-ui/index.html#
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/316f12a4-0b8d-42cd-833d-b08ee2c2ea19)

`/admin/api/v1/eventstreams/{collectionName}/eventsource` 
the body is required, but there is no example indicating how to use it.

**Comment by jobulcke** [comment]
Resolved in https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pull/1312
