### ISSUE TITLE
All rdf data in the server db should have the same mimetype

### ISSUE THREAD

**Issue by pj-cegeka** [Informatievlaanderen/VSDS-LDESServer4J#1310]
Currently in the server, the retention policies and member models are saved to the db as different mimetypes.
The member models are saved as RDF protobuf, the retention policies should preferably also be changed to protobuf.

**Comment by Yalz** [comment]
To dicsuss with developers

**Comment by jobulcke** [comment]
This has been discussed and will not be implemented. Feel free to make a PR and this will be reviewed then
