### ISSUE TITLE
Configure Bucketization + Pagination interval via cron job

### ISSUE THREAD

**Issue by Yalz** [Informatievlaanderen/VSDS-LDESServer4J#1314]
**Is your feature request related to a problem? Please describe.**
Currently, the pagination and bucketization processes are triggered every 15 seconds, however this is a static value randomly chosen. A better (adjustable) interval would be better.

**Describe the solution you'd like**
Use Cron job that uses variable interval

**Comment by Yalz** [comment]
Not configurable, but as a shared Cron value over paginationa and bucketisation

**Comment by jobulcke** [comment]
Available since 3.3.0 with the following spring config property: `ldes-server.fragmentation-cron`
