### ISSUE TITLE
Bucketization and Pagination stops before everything is bucketized and paginated

### ISSUE THREAD

**Issue by jeflaenen** [Informatievlaanderen/VSDS-LDESServer4J#1336]
**Describe the bug**
During ingest, and also when ingest has stopped, it seems that bucketization and pagination is very slow and halts after a certain time.

**Expected behavior**
Bucketization and pagination should be done during ingestion and when ingestion is done.
It should not run behind too far and should not stop before everything has been bucketized and paginated.

**Screenshots**
![image](https://github.com/user-attachments/assets/c5c8264d-bc52-4df9-9d11-4e50e0bf84d7)

**Comment by rorlic** [comment]
After re-testing the page_members count (middle) does increase but very slow (50 mbrs/s) while the paged count (bottom one) does not change.

**Comment by jobulcke** [comment]
Effort has been done

**Comment by jeflaenen** [comment]
🥳
