### ISSUE TITLE
README.md  - additional info required and small style remarks.

### ISSUE THREAD

**Issue by Krieke** [Informatievlaanderen/VSDS-LDESServer4J#136]
Below you can find some links to previously made PR's where I added some comments.

- https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/48521504732415ae32404018fee76b7e59e1c466#r79180614
- https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/48521504732415ae32404018fee76b7e59e1c466#r79180662
- https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/48521504732415ae32404018fee76b7e59e1c466#r79181024
- https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/48521504732415ae32404018fee76b7e59e1c466#r79181160

- https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/f8b0bc5080ac73981de7a07705cceddc60158020#r79178551
- https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/f8b0bc5080ac73981de7a07705cceddc60158020#r79178730
- https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/f8b0bc5080ac73981de7a07705cceddc60158020#r79178845
- https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/f8b0bc5080ac73981de7a07705cceddc60158020#r79178941
- https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/f8b0bc5080ac73981de7a07705cceddc60158020#r79179182
- https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/f8b0bc5080ac73981de7a07705cceddc60158020#r79179472
- https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/f8b0bc5080ac73981de7a07705cceddc60158020#r79179556
- https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/f8b0bc5080ac73981de7a07705cceddc60158020#r79180069
- https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/f8b0bc5080ac73981de7a07705cceddc60158020#r79182032
- https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/f8b0bc5080ac73981de7a07705cceddc60158020#r79182231

**Comment by WLefever-Cegeka** [comment]
partly addressed in #166

**Comment by WLefever-Cegeka** [comment]
Regarding split code coverage. Since SonarQube v6.x all coverage is merged into one metric. Using jacoco you can request code coverage of only unit tests/ integration tests. Added documentation for that in #170

**Comment by zargha** [comment]
Sat together with @WLefever-Cegeka and went through all the comments from Daniel. Modifications are made to the documentation. The issue can be closed.

**Comment by WLefever-Cegeka** [comment]
Thanks, @zargha
