### ISSUE TITLE
Please allow xsd:string in addition for xsd:dateTime for values in time-based fragmentation

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-LDESServer4J#1392]
Please allow xsd:string in addition for xsd:dateTime for values in time-based fragmentation.
This will allow to time-fragment anything which complies to the [OSLO Generiek Basis](https://data.vlaanderen.be/doc/applicatieprofiel/generiek-basis/) - see [Gestructureerde Identificator](https://data.vlaanderen.be/doc/applicatieprofiel/generiek-basis/#Gestructureerde%20Identificator)

**Comment by jobulcke** [comment]
Resolved in #1403
