### ISSUE TITLE
Vulnerability: Update image versions

### ISSUE THREAD

**Issue by Yalz** [Informatievlaanderen/VSDS-LDESServer4J#157]
![image](https://user-images.githubusercontent.com/15772440/184098908-2df785ba-06e4-469a-9f43-f2d42a287071.png)

**Comment by Krieke** [comment]
Update on the detected vulnerabilities for artifact https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pkgs/container/ldes-server/30879985?tag=20220729T1224
![image](https://user-images.githubusercontent.com/19797982/184671754-5f93a7ac-1968-46f4-af8f-6ba2e7037f3e.png)

**Comment by Krieke** [comment]
Fix for artifact version: 20220816t1248
