### ISSUE TITLE
Parsing configuration properties who are left empty

### ISSUE THREAD

**Issue by Yalz** [Informatievlaanderen/VSDS-LDESServer4J#175]
### What went wrong
When starting the server in our E2E repo for a timedbased, we provide empty values for geobased properties.
However this causes the following issues:

- max zoom level: 

  > Failed to bind properties under 'geospatial.max-zoom-level' to int:
      Property: geospatial.max-zoom-level
      Value: ""
      Origin: System Environment Property "GEOSPATIAL_MAXZOOMLEVEL"
      Reason: failed to convert java.lang.String to int (caused by java.lang.IllegalArgumentException: A null value cannot be assigned to a primitive type)
  
  #### Solution
  To only load in geospatial/timebased configuration values based on the provided fragmentation type 

- Default (lambert72) Coordinate converter is being called when fragmentation type:

  > Parameter 1 of constructor in be.vlaanderen.informatievlaanderen.ldes.server.fragmentisers.geospatial.bucketising.GeospatialBucketiser required a bean of type 'be.vlaanderen.informatievlaanderen.ldes.server.fragmentisers.geospatial.bucketising.CoordinateConverter' that could not be found.

  #### Solution
  Add conditional on property when geobased fragmentation is selected by config + matchIfMissing to false

**Comment by WLefever-Cegeka** [comment]
I fixed the issue in https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pull/192 ? Can you try again with the current tag: 20220831t1755?
