### ISSUE TITLE
[Tracing] end2end missing

### ISSUE THREAD

**Issue by Krieke** [Informatievlaanderen/VSDS-LDESServer4J#254]
One would expect the a new span context would be created the moment a certain HTTP or MongoDB action is performed that a (new) span context is created / updated.  For MongoDB there are tests which add these, but these will not be added during operational service. The whole idea behind this tracing is that one at least can validate this trace contexts during test / staging phase.

Modules with no trace impl are:
* ldes-server-infra-mongo
* ldes-server-port-fetch-rest
* ldes-server-port-ingestion-rest

**Comment by Yalz** [comment]
Hi Daniel, 
Spring Data automagically adds traces for database interactions.
Same thing goes for HTTP interactions. 
There is an example available on the Metrics page of [confluence ](https://vlaamseoverheid.atlassian.net/wiki/spaces/VSDSPUB/pages/6118377371/Tracing)

**Comment by Krieke** [comment]
@Yalz Pfff no DI so difficult to notice. But when they are added it is top
