### ISSUE TITLE
[README.md] Trace

### ISSUE THREAD

**Issue by Krieke** [Informatievlaanderen/VSDS-LDESServer4J#255]
The documentation of tracing could be more informative:
* which modules contain tracing
* what is the sampling rate when tracing is enabled
* are there any specific tags used?
* is there a naming convention for these tags => NO => why not?
* The export of traces can be disabled with the following parameter: => is not correct, according to the documentation tracing service is disabled. => that is different then disabling the export of traces. If one expect the latter, tracing sampling still might impact the service performance.

**Comment by Yalz** [comment]
* By default, all rest and data modules have tracing auto implemented. This in practice means the ingest, fetch and mongo module. Additionally, some extra traces were implemented on important fragmentation points.
* The sampling rate is recommended to be set on 1.0, however this is a configurable value as can be found in the readme.
* there is no additional tags added on spans. This might be reevaluated if needed.
