### ISSUE TITLE
Enable compression for RDF mimetypes

### ISSUE THREAD

**Issue by sandervd** [Informatievlaanderen/VSDS-LDESServer4J#317]
As RDF mimetypes are text based, the output of the server could be compressed to save bandwidth.

https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.server

**Comment by sverholen** [comment]
We transparantly compress data in the k8 deployment.

If you want to enable compression in the server, use this config:
`# Enable response compression
server.compression.enabled=true
# The comma-separated list of mime types that should be compressed
server.compression.mime-types=application/ld+json,text/turtle,application/n-quads,application/n-triples
# Compress the response only if the response size is at least 1KB
server.compression.min-response-size=1024`

See also [VSDSPUB-113](https://vlaamseoverheid.atlassian.net/browse/VSDSPUB-113).
