### ISSUE TITLE
Document modules

### ISSUE THREAD

**Issue by sandervd** [Informatievlaanderen/VSDS-LDESServer4J#346]
What does each module do? How do they work together?

**Comment by Yalz** [comment]
High level developer documentation + architecture documentation ?

**Comment by Yalz** [comment]
to discuss in design session

**Comment by sandervd** [comment]
e.g. ldes-fragmentisers, ldes-queues, ldes-server-application, ldes-server-domain, ldes-server-infra-mongo, ldes-server-port-fetch-rest, ldes-server-port-ingestion-rest
What is the resposnibility of each module? How are they depending on one another? Which modules are implementations of an interface, that could be replaced with something else?

**Comment by Yalz** [comment]
Component diagram,
How independent are components?
Which interfaces need to be implemented for new components ?

In short, a guide to start and create new modules
