### ISSUE TITLE
Cannot request application/n-triples

### ISSUE THREAD

**Issue by pj-cegeka** [Informatievlaanderen/VSDS-LDESServer4J#357]
for example executing command:
```
curl -i -H "accept: application/n-triples"  http://localhost:8080/mobility-hindrances/by-time
```
expected result: `HTTP/1.1 200`
actual result: `HTTP/1.1 406`

**Comment by Yalz** [comment]
This is due to the supportedMediaTypes in the TreeNode- and EvenStreamHttpConverter limiting the accept headers to turtle, JSON-LD and N-quads. Whilst further in the code, we parse the language checking if there is a match with Jena's supported languages
