### ISSUE TITLE
Apply TimeBased Fragmentation based on the properties within a member.

### ISSUE THREAD

**Issue by WLefever-Cegeka** [Informatievlaanderen/VSDS-LDESServer4J#368]
Currently, the relations in timebased fragmentation are based on the time at which the fragment is created. See `String fragmentValue = LocalDateTime.now().format(formatter);`.
However, this is not correct. For a correct timebased fragmentation, Members of the fragment should be checked and their value for a given property should be used to create the correct relations.
Example:
Timebased fragmentation is done using the property `http://www.w3.org/ns/prov#generatedAtTime` and members contain statements as the following one:
```
<https://private-api.gipod.beta-vlaanderen.be/api/v1/mobility-hindrances/10228622/483> <http://www.w3.org/ns/prov#generatedAtTime> "2020-12-28T09:36:37.127Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
```
Then the value for the relation should be computed on the values "2020-12-28T09:36:37.127Z".

**Comment by Tomvbe** [comment]
Closing this issue as this module has been marked as deprecated
