### ISSUE TITLE
Curl to local server without accept header returns error

### ISSUE THREAD

**Issue by RubenHuybrighs** [Informatievlaanderen/VSDS-LDESServer4J#376]
**Describe the bug**
Curl to locally built server returns error message. Without accept header uses "Accept: */* " by default.

**To Reproduce**
1. curl http://localhost:8080/mobility-hindrances
2. Result: "FETCH: RDF format application/json is not a supported format."

Returns correct result:
curl http://localhost:8080/mobility-hindrances --header "Accept: text/turtle" 

**Expected behavior**
Server returns response in the correct default format: turtle.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.1

**Comment by WLefever-Cegeka** [comment]
Hi Ruben,
This is a Spring Boot Issue.
For some unknown reason Spring Boot uses 'application/json' when the accept header is empty. Likely due to the fact that that one is listed first in MediaType class.
I created a fix so that an empty accept header is treated as turtle.

**Comment by RubenHuybrighs** [comment]
Issue fixed
