### ISSUE TITLE
Group all fragmentation updates together and commit to database in one transaction

### ISSUE THREAD

**Issue by WLefever-Cegeka** [Informatievlaanderen/VSDS-LDESServer4J#470]
Currently every fragmentation strategy applies updates to the database separately. If the server would break down, it's possible that part some fragmentation strategies have already been applied and other not. This would result in inconsistent results. Hence, it would be better to group them all together and apply them in one transaction.
Also from a performance point of view it's better to group all updates on fragments and apply them in one go.

**Comment by Yalz** [comment]
In the current Event based approach, this proposal is no longer valid
