### ISSUE TITLE
Snapshot conforms OSLO LDES : https://data.vlaanderen.be/doc/applicatieprofiel/ldes/

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#511]
***Prerequisites:***
Run the test described at: [ 025.server-snapshot-ldes](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/demos/025.server-snapshot-ldes)
With LDES Server docker image:  ghcr.io/informatievlaanderen/ldes-server:20230407T1308

***Scenario:*** 
Request the first snapshot : `curl http://localhost:8080/mobility-hindrances/snapshot-2023-04-14T07:18:09.829596412`

***Current result:***
```
@prefix ldes:  <https://w3id.org/ldes#> .
@prefix prov:  <http://www.w3.org/ns/prov#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix terms: <http://purl.org/dc/terms/> .
@prefix tree:  <https://w3id.org/tree#> .

<http://localhost:8080/mobility-hindrances/snapshot-2023-04-14T07:18:09.829596412>
        rdf:type       tree:Node ;
        tree:relation  [ rdf:type   tree:Relation ;
                         tree:node  <http://localhost:8080/mobility-hindrances/snapshot-2023-04-14T07:18:09.829596412?pageNumber=1>
                       ] .

<http://localhost:8080/mobility-hindrances>
        rdf:type            ldes:EventStream ;
        ldes:timestampPath  prov:generatedAtTime ;
        ldes:versionOfPath  terms:isVersionOf ;
        tree:view           <http://localhost:8080/mobility-hindrances/snapshot-2023-04-14T07:18:09.829596412> .
```
According to the definition in the [OSLO LDES](https://data.vlaanderen.be/doc/applicatieprofiel/ldes/), the snapshot cannot be seen as a `tree:view` to the `tree:Collection`.

Therefore, I think when requesting the snapshot : `curl http://localhost:8080/mobility-hindrances/snapshot-2023-04-14T07:18:09.829596412`
We should have something like:

```
@prefix ldes: <https://w3id.org/ldes#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix terms: <http://purl.org/dc/terms/> .
@prefix tree: <https://w3id.org/tree#> .
@prefix oslo: <https://data.vlaanderen.be/ns/ldes#>
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>

<http://localhost:8080/mobility-hindrances/snapshot-2023-04-14T07:18:09.829596412>
       rdf:type      oslo:Snapshot ;  
       oslo:snapshotVan <http://localhost:8080/mobility-hindrances>
       oslo:snapshotTot "2023-04-14T07:18:09.829596412"^^xsd:dateTime
       tree:relation [ rdf:type  tree:Relation ;
                        tree:node <http://localhost:8080/mobility-hindrances/snapshot-2023-04-14T07:18:09.829596412?pageNumber=1>
                      ] .
```

Please feel free to leave a comment.
Thanks
XD

**Comment by WLefever-Cegeka** [comment]
Hi @xdxxxdx ,
It's correct that snapshots are now not correctly returned. We'll pick the issue up when working on https://vlaamseoverheid.atlassian.net/jira/software/projects/VSDSPUB/boards/681/backlog?selectedIssue=VSDSPUB-563

**Comment by jeflaenen** [comment]
Snapshotting and how is should look like is under discussion. This issue will be picked up when the discussion is finalized.

**Comment by Yalz** [comment]
Snapshotting is discontinued
