### ISSUE TITLE
ERROR XJ004: Database '/tmp/Databases/SpatialMetadata' not found..  LDES Server crashed

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#529]
**Describe the bug**

- ERROR XJ004: Database '/tmp/Databases/SpatialMetadata' not found..  LDES Server crashed
- E2E scenario: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/demos/022.server-upgrade-with-ldio
- Tags: (sprint 24)
-  LDES_SERVER_TAG=20230407T1308 (ghcr.io/informatievlaanderen/ldes-server:20230407T1308) (Sprint24 by @rorlic )

**To Reproduce**
1. Follow the step-by-step scenario of the E2E scenario: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/demos/022.server-upgrade-with-ldio
2. Till the step to run:  `docker compose up new-ldes-server -d`

**Expected behavior**
new-ldes-server up and running

**Current behavior**
new-ldes-server crashed
2023-04-19 12:15:00 ERROR XJ004: Database '/tmp/Databases/SpatialMetadata' not found.
logs: 
[ldesServerUpgrade.txt](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/11272514/ldesServerUpgrade.txt)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows +WSL
-  Docker: Docker Engine v20.10.22

**Comment by xdxxxdx** [comment]
Remove:
```
volumes:
  - ../../data/epsg:/tmp/Database
```
In the docker file.
Got another error:
2023-04-20 11:44:26 2023-04-20T09:44:26.496Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
Full log:[Error2.txt](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/11284777/Error2.txt)

**Comment by Tomvbe** [comment]
now your epsg database is fine but you have an error on the config
`Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'ldes.collectionname'`
This is because the configuration of the server changed this sprint (cfr commit of Ruben on 17/04 on the docker-compose file). So you are using new config on an older server version that expects old config

**Comment by xdxxxdx** [comment]
Remove:

```
volumes:
  - ../../data/epsg:/tmp/Database
```
From: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/demos/022.server-upgrade-with-ldio/docker-compose.yml 

Works for E2E repo tag: 9c3d00247970e0dc7732c09fdb9a6f0a3a358d72 (sprint 24)

**Comment by Tomvbe** [comment]
great, that volume helps with performance as we provide a epsg database from ../../data/epsg but for some reason that path could not be found on your local computer and caused an issue. So you can fix the issue by either omitting the volume (makes things work but slower) or make sure that directory exists.
