### ISSUE TITLE
Use LdesFragmentIdentifier as identifier for the LdesFragment class

### ISSUE THREAD

**Issue by WLefever-Cegeka** [Informatievlaanderen/VSDS-LDESServer4J#537]
Pieter-Jan is working on a class LdesFragmentIdentifier in the context of snapshotting. It might be wise to use this class as the identifier for the LdesFragment class.
The LdesFragmentIdentifier consists of two attributes ViewName and List of FragmentPairs and has relevant methods such as:
* generating the id from its attributes
* generating an instance of LdesFragmentIdentifier from an id (a String)

**Comment by pj-cegeka** [comment]
The LdesFragmentIdentifier class is now being used in the server.
