### ISSUE TITLE
ERROR 1 --- [nio-8080-exec-1] s.r.e.RestResponseEntityExceptionHandler : Collection with name version could not be found.

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#560]
**Prerequisites:**
Commit tags (sprint 25):
VSDS-LDESServer4J: e1c62110b5926f151f75b3daf26254c83a87c1a6

**To Reproduce:**
1. Go to the working directory under `/VSDS-LDESServer4J`
2. Run `docker-compose up`

**Expected behavior**
LDES server is built and started with the local configuration `- ./docker-compose/config.local.env` as described at https://github.com/Informatievlaanderen/VSDS-LDESServer4J/blob/main/compose.yml
No error in the log

**Current result**
LDES Server is running with following error in the log:
2023-05-02 10:34:24 2023-05-02T08:34:24.778Z ERROR 1 --- [nio-8080-exec-1] s.r.e.RestResponseEntityExceptionHandler : Collection with name version could not be found.

![image](https://user-images.githubusercontent.com/15314807/235622879-ad764ba9-569f-4850-836d-1c10dfd06255.png)

Full log at: 
[Errorlog.txt](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/11371326/Errorlog.txt)

**Comment by WLefever-Cegeka** [comment]
Hi @xdxxxdx ,
Thanks for logging the issue. I tried to replay it this morning, but it seems like the docker-compose does start normally (both on the provided tag as on the latest version of main) (logs are attached to this message).
[output.txt](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/11372692/output.txt)
I noticed something strange in your logs. Line 113-114 show exceptions with the name 'api' and 'apis'. However, these terms are nowhere in the project (check via crtl + f). Is it possible that you have configured something differently (which could also be the cause of the error)?: 
```
2023-05-02 10:31:16 2023-05-02T08:31:16.266Z ERROR 1 --- [nio-8080-exec-8] s.r.e.RestResponseEntityExceptionHandler : Collection with name api could not be found.
2023-05-02 10:31:16 2023-05-02T08:31:16.301Z ERROR 1 --- [nio-8080-exec-9] s.r.e.RestResponseEntityExceptionHandler : Collection with name apis could not be found.
```

**Comment by xdxxxdx** [comment]
Hello @WLefever-Cegeka ,

Thanks for the reply.
The LDES-Server repo is untouched with sprint 25 tag: 
![image](https://user-images.githubusercontent.com/15314807/235899844-fd59b8ae-95f2-40a0-a7cc-eb755696e174.png).
I just reproduced issue.

[error_560.txt](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/11381851/error_560.txt)

Please see here.
You need to wait a while after the Server is started to reproduce the error.

Thanks

**Comment by xdxxxdx** [comment]
The issue cannot be seen: revision: [1a7a8bac03adf97e6108feda34a19bf99408123e](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/1a7a8bac03adf97e6108feda34a19bf99408123e)
