### ISSUE TITLE
Revise the InMemoryCollection pattern

### ISSUE THREAD

**Issue by WLefever-Cegeka** [Informatievlaanderen/VSDS-LDESServer4J#566]
Currently we use an in memory collection which reflects the contents of the database for shapes, views and collections.
The initial reason why this was added was in the context of shapes:
Shapes were constantly retrieved by the ingest service and the memory spent on keeping a few shapes in memory is neglectable. Even more if you consider the performance improvement of retrieving a shape from a memory collection versus retrieving a shape from a database.
However, after adding views I realized that there's maybe a better way of doing this by keeping the collection of shapes as an attribute in the ingest service. This is also how it's done for the fragmentation process and retention process in the case of views.
The InMemoryCollection can then be deleted.

PS: This is maybe also how @jobulcke initially intended it, but for some reason I convinced him otherwise.
![InMemoryCollection](https://user-images.githubusercontent.com/104509963/235908018-9657a46b-ed2f-44af-8c37-ec5500248a71.png)

**Comment by Yalz** [comment]
This seems to already have been resolved by now. @WLefever-Cegeka can you verify?
