### ISSUE TITLE
Upgrade LDES Collection creates un-linked/unreachable fragments

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#567]
**Prerequisite:**
Tags for sprint 25
- VSDS-LDES-E2E-testing: b50091609d92389b58c6c5c6030c83c77c95a467
- LDES_OLD_SERVER_TAG=20221107t0923
- LDI_WORKBENCH_NIFI_TAG=20230424T152652
- LDI_ORCHESTRATOR_TAG=20230419T081024
- LDES_SERVER_TAG=20230424T0954

**Scenario:**
1. follow the step-by-step solution as described at: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/demos/021.server-upgrade-with-nifi
2. After Test-Set Up, a time-based fragment is created on the old LDES Server: http://localhost:8080/devices-by-time?generatedAtTime=2023-05-03T12:57:23.799Z
![Capture](https://user-images.githubusercontent.com/15314807/235926010-f30ec077-1c9c-44a0-9d02-7a9a562a86b5.PNG)
3. Continue the test steps -> remove the old server -> start new server -> restart HTTP Sender.

**Current result:**
When starting the new LDES server, a new fragment is created at the same time. : http://localhost:8080/devices/devices-by-time?generatedAtTime=2023-05-03T13:00:49.127Z. The root point of the new LDES Server is pointing to the newly created fragment, 
![image](https://user-images.githubusercontent.com/15314807/235928517-e14d77d7-d3c0-4ae2-ac28-73ca568dcee5.png)
There is no relation in this new fragment linking back the old LDES Server fragment(s): in the current case: http://localhost:8080/devices-by-time?generatedAtTime=2023-05-03T12:57:23.799Z

![image](https://user-images.githubusercontent.com/15314807/235928849-14d3d891-6893-4375-a32c-4f11fd487835.png)

 ldesfragment collection: please see: 
[ldesfragment.zip](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/11382966/ldesfragment.zip)

**Expected result:**
The fragments created by the old LDES Server: http://localhost:8080/devices-by-time?generatedAtTime=2023-05-03T12:57:23.799Z should not be unreachable.

**Comment by xdxxxdx** [comment]
This issue is resolved by the commit: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/commit/ad89651a00c27ca5ff34efd820180de9d77d49c5#diff-cd33eaf9722589860ffa7c8121f9dd6e96739f9c37fd1d399146cc7445a66142

With adding `'MONGOCK_MIGRATIONSCANPACKAGE_2=be.vlaanderen.informatievlaanderen.ldes.server.infra.mongo.mongock.changeset3'` to the docker file.

After the server upgrade: the URL of the fragment is modified to the new ldes serve format

_id of the ldesfragment collection On LDES_OLD_SERVER_TAG=20221107t0923

![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/b5de4197-8420-4661-9a8d-ed3be7465a55)

On /ldes-server:20230424T0954: is changed to:
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/868f4691-f892-4f65-8038-14cadc6a0771)

@WLefever-Cegeka  @rorlic ,
Please have a look at this, and see if it is expected behavior. Cause in the https://github.com/Informatievlaanderen/VSDS-LDESServer4J/tree/main/ldes-server-infra-mongo/mongock-changeset-3. There is no doc indicating the `_id `of the fragment will also be changed.
Thanks

**Comment by Tomvbe** [comment]
Closing this, as it is expected behavior that was not added in changeset-3 but in changeset-4.

https://github.com/Informatievlaanderen/VSDS-LDESServer4J/tree/main/ldes-server-infra-mongo/mongock-changeset-4

**Comment by xdxxxdx** [comment]
To be validated with sprint 28

**Comment by xdxxxdx** [comment]
ldes/ldes-server:1.1.0-SNAPSHOT
