### ISSUE TITLE
Update Member Id extraction so that MemberType is no longer used

### ISSUE THREAD

**Issue by WLefever-Cegeka** [Informatievlaanderen/VSDS-LDESServer4J#568]
MemberType is an configuration parameter which allows to easily extract an id for a member:
```
 model
      .listStatements(null, RdfConstants.RDF_SYNTAX_TYPE, ResourceFactory.createResource(memberType))
```
However, with the dynamical configuration of the server, we're unable to pass this parameter. Hence it would be better to update the code and take the identifier of the 'entrypoint' of the linked data object (see image).
![image](https://user-images.githubusercontent.com/104509963/235930706-62d29bf7-dce4-490f-8648-e8e28cd58024.png)

**Comment by Tomvbe** [comment]
We added the memberType back to the config as extraction algorithms bring too many problems for the time being.
