### ISSUE TITLE
CollectionNotFoundException and MissingEventStreamException are almost the same

### ISSUE THREAD

**Issue by jobulcke** [Informatievlaanderen/VSDS-LDESServer4J#569]
In the package `be.vlaanderen.informatievlaanderen.ldes.server.domain.exceptions` are both `CollectionNotFoundException` and `MissingEventStreamException` defined, which are both used to throw when an eventstream collection cannot be found. 

I suggest to drop one of the two exceptions, so that we don't have two seperate exceptions that are both thrown with the same cause

**Comment by Tomvbe** [comment]
Related to the more general issue on similar exceptions: https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/661

**Comment by ASDasd341** [comment]
should i look into this?
