### ISSUE TITLE
Implement re-usable exceptions

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-LDESServer4J#661]
We have a lot of different exceptions that are only used in very specific cases which could be easily merged together in a common NotFoundException, NotUniqueException, etc. instead of creating these kind of exceptions in many different flavors.

**Comment by WLefever-Cegeka** [comment]
Agree, moreover since we are treating them all in a similar way when returning the http status and message :-)

**Comment by Tomvbe** [comment]
When picking this issue up, the following issue can be done at the same time: https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/569
