### ISSUE TITLE
Deletion of collection is exceptionally slow

### ISSUE THREAD

**Issue by Yalz** [Informatievlaanderen/VSDS-LDESServer4J#680]
**Describe the bug**
Deletion of a rather small collection takes more than 10 min. 
Needs  a deep dive into performance.

**To Reproduce**
1. Have a collection with around 13k members
2. Perform /admin/api/v1/eventstreams/{collectionName}
3. See how deletion takes more than 10 min

**Comment by Yalz** [comment]
+ expected member_sequence of collection to be deleted

**Comment by jobulcke** [comment]
A more performant solution can be found in the module `ldes-server-port-ingest`. There is an extra method added to the `MemberRepository` in this module which deletes all the existing members by a collection name. (This also brings the implementation of an extra JPA method in the corresponding mongo module).

To optimize the deletion of this process in the original modules, an extra method will need to be provided in the `MemberRepository` which deletes all the members by a collection name in the domain module and the `MemberIngestServiceImpl.handleEventStreamDeletedEvent` will need a slightly other implementation

**Comment by Tomvbe** [comment]
There was still an issue where the view deletion triggered a one by one adjustment of all members before they were actually deleted. This is fixed in https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pull/718. Collections with millions of members can now be deleted in a couple of seconds.
