### ISSUE TITLE
Server crashes if no timestampPath and/or versionOfPath provided

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-LDESServer4J#704]
**Describe the bug**
If you try to create a collection using the admin API but leave out timestampPath and/or versionOfPath, the config passes the shacl validation but the server returns a status 500 / Internal Server Error.

**To Reproduce**
1. Launch a server with some basic config
2. POST a LDES definition (see below) using the admin endpoint `/admin/api/v1/eventstreams`

**Actual behavior**
A server error is returned such as:
`{"timestamp":"2023-06-06T09:20:41.413+00:00","status":500,"error":"Internal Server Error","path":"/admin/api/v1/eventstreams"}`

**Expected behavior**
No server error is returned.
If both paths are required, the shacl shape should enforce this.

**Additional context**
Example offending LDES definition:
```
@prefix ldes:    <https://w3id.org/ldes#> .
@prefix tree:    <https://w3id.org/tree#>.
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix prov:    <http://www.w3.org/ns/prov#> .
@prefix xsd:     <http://www.w3.org/2001/XMLSchema#> .
@prefix server:  <http://example.org/> .
@prefix sh:      <http://www.w3.org/ns/shacl#> .

@base <http://localhost:8080> .

</connections> a ldes:EventStream ;
	tree:shape [ a sh:NodeShape ] ;
	ldes:timestampPath prov:generatedAtTime ;
	server:memberType <http://semweb.mmlab.be/ns/linkedconnections#Connection> ;
	server:hasDefaultView "false"^^xsd:boolean .
```

**Comment by Tomvbe** [comment]
Fix merged to develop
