### ISSUE TITLE
Specify how to set time/geo fragment properties.

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#716]
For the API docs:  http://localhost:8080/v1/swagger-ui/index.html

- For time-based fragmentation.

As the example at:  https://informatievlaanderen.github.io/VSDS-Tech-Docs/docs/quickstart.html.
When posting a new collection to the ldes server.
` ldes:timestampPath dcterms:created ;` is set.
**_Please specify what is the use of this key?_**

Also as stated, the default time-based fragmentation property is` http://www.w3.org/ns/prov#generatedAtTime`. Please also specify how to modify time-based `fragmentationProperty` ?

- For geo-based fragment
Similar question as the time-based one, please specify how to configure the geo-based fragment property

**Comment by Yalz** [comment]
Link to updated documentation: https://informatievlaanderen.github.io/VSDS-LDESServer4J/configuration/fragmentations/timebased
