### ISSUE TITLE
Performance issues with deleting views

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-LDESServer4J#721]
Describe the bug
Deletion of a rather small view takes more than 10 min.
Needs a deep dive into performance.

To Reproduce

    Have a view with around 13k members
    Performadmin/api/v1/eventstreams/{collection}/views/{view}
    See how deletion takes more than 10 min

**Comment by xdxxxdx** [comment]
Also very long when taking a snapshot, please also have a look.

**Comment by Tomvbe** [comment]
Fixed in https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pull/731

**Comment by Tomvbe** [comment]
Reopened this issue as the deletion of views is slow again after splitting the retention logic to a separate module.
In `DeleteEventHandler` we have the following listener: 

```	@EventListener
	public void handleViewDeletedEvent(ViewDeletedEvent event) {
		String viewName = event.getViewName().asString();
		memberPropertiesRepository.getMemberPropertiesWithViewReference(viewName)
				.forEach(memberProperties -> memberRemover.removeMemberFromView(memberProperties, viewName));
	}```

This iterates all members of a view one by one when a view is deleted. When a view has 1 mio members, this takes ages..

**Comment by jobulcke** [comment]
Fixed in https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pull/1232
