### ISSUE TITLE
API POST /admin/api/v1/{collection}/snapshots: Unable to create snapshot. member xx does not have a valid timestampPath or versionOfPath

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#727]
**Prerequisites:** 
- ldes/ldes-server:1.0.0-SNAPSHOT
- Follow the https://informatievlaanderen.github.io/VSDS-Tech-Docs/docs/quickstart.html.
- Observations collection is created 
- Observation member  <urn:ngsi-ld:WaterQualityObserved:woq:1/2023-03-12T18:31:17.003Z> is ingested to the server

**To Reproduce**
1. Go to http://localhost:8080/v1/swagger-ui/index.html#/Snapshots/createSnapshot
2. Click on 'Snapshot' API, POST /admin/api/v1/{collection}/snapshots 
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/27eaa1e7-cd64-4722-a1a3-f0db26d50ac5)
3. sent a POST request to the admin API to ask for a snapshot for the observations collection 

**Expected behavior**
A snapshot is created, 200 OK is returned.

**Current behavior**
Error: response status is 500
Unable to create snapshot.
Cause: Member observations/urn:ngsi-ld:WaterQualityObserved:woq:1/2023-03-12T18:31:17.003Z does not have a valid timestampPath or versionOfPath

**Screenshots**
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/2219f1df-16d9-484d-8287-a071ce0de5ee)

**Comment by Tomvbe** [comment]
I don't know how well this is documented but having these properties is a prerequisite of snapshotting. Without them, it is not possible to  make a snapshot. The current implementation of snapshots are version and timebased.

**Comment by ASDasd341** [comment]
can i check into this issue?

**Comment by Yalz** [comment]
Snapshotting is discontinued
