### ISSUE TITLE
Elaboration of  POST /admin/api/v1/eventstreams/{collections}/views API

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#728]
Now inside the http://localhost:8080/v1/swagger-ui/index.html#/m,  for POST /admin/api/v1/eventstreams/{collections}/views API.
There are three examples of added retention views/policies.

**It is very confusing to me, is this API for adding fragmentation views or retention policies, or both?**

from my perspective, if this API is for adding fragmentation views to the collection.
Examples of how to add by-page, time-based, geo-based, substring-based
e.g.
```
@prefix ldes: <https://w3id.org/ldes#> .
@prefix tree: <https://w3id.org/tree#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix server: <http://localhost:8080/mobility-hindrances/> .
@prefix collection: </mobility-hindrances/> .
@prefix example: <http://example.org/> .

collection:time-based tree:viewDescription [
                 ldes:retentionPolicy [
                     a ldes:DurationAgoPolicy  ;
                     tree:value "PT2M"^^xsd:duration ;
                 ] ;
                 example:fragmentationStrategy [
                     a example:Fragmentation ;
                     example:name "timebased" ;
                     example:memberLimit "20" ;
                 ] ;
             ].

```
need to be added.

Thanks

**Comment by Tomvbe** [comment]
+1, this should be better documented

**Comment by Tomvbe** [comment]
Closing this as examples with the different fragmentation strategies were added later on. Now all retention policies and fragmentation strategies are included
