### ISSUE TITLE
GRAR LDES semantic error

### ISSUE THREAD

**Issue by samuvack** [Informatievlaanderen/VSDS-LDESServer4J#748]
There is a semantic error in the GRAR LDES (addresses). Is this due to the Kafka topics of GRAR or the conversion to LDES?
https://grar.smartdataspace.dev-vlaanderen.be/addresses/by-time?generatedAtTime=2023-03-02T08:29:46.287Z

This is the OSLO implementation model: https://basisregisters.vlaanderen.be/assets/oslo/doc/implementatiemodel/adressenregister/ontwerpstandaard/2022-06-30/html/overview.jpg

But streetname has the terms:isVersionOf predicate:
<https://data.vlaanderen.be/id/straatnaam/44854>
        terms:isVersionOf     <https://data.vlaanderen.be/id/adres/2101006> ;

But this bug doesn't occur consistently:
<https://data.vlaanderen.be/id/straatnaam/44852>
        relation:self  "https://api.basisregisters.staging-vlaanderen.be/v2/straatnamen/44852" ;
        <https://data.vlaanderen.be/ns/adres#Straatnaam>

![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15192194/9e2c7a06-9534-4c02-828a-abaa13160c7e)

**Comment by Yalz** [comment]
As issue is now stale and the belonging server is no longer present, closing the ticket
