### ISSUE TITLE
LDES Member should have actual ID

### ISSUE THREAD

**Issue by ajuvercr** [Informatievlaanderen/VSDS-LDESServer4J#76]
Hi

I took a look into this repository so I don't have to implement already existing code :stuck_out_tongue: 
There is a lot of boilerplate present but no 'real' LDES Server functionality (please correct me if I'm wrong, java is not my first language)

I stumbled across something strange though (see snippet). Here a jsonld object is converted into a MemberEntity thing which is a Member with an ID but the ID used is just the hashcode of the object. This feels unpolished and possible just some code that is in the pipeline to get changed. If not this is a big issue, the id of a member is a URI across the `world` not just a HashCode.

https://github.com/Informatievlaanderen/VSDS-LDESServer4J/blob/eb01104220d9fa6824d5e6d8f5b90500f5664f2e/ldes-server-infra-mongo/src/main/java/be/vlaanderen/informatievlaanderen/ldes/server/infra/mongo/converters/LdesMemberConverterImpl.java#L22-L29

You can close this issue if the problem is invalid.

**Comment by pietercolpaert** [comment]
This gives a new identifier to a member that already has an identifier. I also think this _must_ be the member id from the linked data for consistency.

**Comment by Yalz** [comment]
As part of our last rework, the LDES member is being stored with the member ID as entity id.
