### ISSUE TITLE
Add datatype tree:Node 

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#765]
Docker image: [ldes/ldes-server:1.1.0-SNAPSHOT](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=#)
According to the Tree Spec: https://treecg.github.io/specification/#traversing

>  A `tree:Relation` MUST have one `tree:node` object of the type`
> tree:Node`.

Our current output e.g.:

```
@prefix kbo:   <http://localhost:8080/kbo/> .
@prefix ldes:  <https://w3id.org/ldes#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix shacl: <http://www.w3.org/ns/shacl#> .
@prefix terms: <http://purl.org/dc/terms/> .
@prefix tree:  <https://w3id.org/tree#> .

kbo:by-page  rdf:type  tree:Node ;
        tree:relation  [ rdf:type   tree:Relation ;
                         tree:node  <http://localhost:8080/kbo/by-page?pageNumber=1>
                       ] .

<http://localhost:8080/kbo>
        rdf:type            ldes:EventStream ;
        ldes:timestampPath  terms:issued ;
        ldes:versionOfPath  terms:isVersionOf ;
        tree:view           kbo:by-page .

kbo:shape  rdf:type        shacl:NodeShape ;
        shacl:deactivated  true ;
        shacl:nodeShape    [ shacl:closed         true ;
                             shacl:propertyShape  [] 
                           ] .

```
I think a datatype should be added e.g.
`tree:node  "<http://localhost:8080/kbo/by-page?pageNumber=1>"^^tree:Node;`

Please feel to leave comment.
Thanks

**Comment by WLefever-Cegeka** [comment]
Hi @xdxxxdx ,
It seems to me that `http://localhost:8080/kbo/by-page?pageNumber=1` is an entity and therefore the current statement `<someRelation> tree:node  <http://localhost:8080/kbo/by-page?pageNumber=1>` is correct. The suggestion you make would treat "<http://localhost:8080/kbo/by-page?pageNumber=1>" as a literal, in your case a literal of type `<https://w3id.org/tree#Node>`. That doesn't seem correct.

**Comment by xdxxxdx** [comment]
Hi @WLefever-Cegeka 
Thanks for reply.
Yes, you are right, that make sense.
