### ISSUE TITLE
Re-evaluate removal of members when a view is deleted

### ISSUE THREAD

**Issue by WLefever-Cegeka** [Informatievlaanderen/VSDS-LDESServer4J#769]
Currently, the removal of a member from the database is evaluated after the evaluation of the retention policies of a view on that member. This works as long as the views of a collection are static.
Since the introduction of the admin api, it is possible to add/delete views. Hence, there's a need to re-evaluate removal of members from the database when a view is deleted. Otherwise the following scenario is possible:

1. Collection has two views: one with a retention policy and one without a retention policy
2. All members of the collection match the retention policy and are thus removed from the first view. However, they are not removed from the database since they are still referenced in the second view.
3. The second view is deleted.

Now, you come in a situation where:
* the members are already removed from view one (so there won't be any new evaluation of the members in this view)
* the members still exist in the database, although they are not referenced anywhere.

**Comment by pj-cegeka** [comment]
This issue has been fixed with the refactoring of the retention module.
