### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by Yalz** [Informatievlaanderen/VSDS-LDESServer4J#77]
As I was trying to start up the project locally (not using docker), I noticed the documentation refers to a nonexisting application config

**Comment by Krieke** [comment]
What I would like to see for a minimum is:
* How to build
* How to run tests
* How to create docker image

Are is it expected that one uses the GitHub actions for this?  

It is nice that you mention Intellij, but building from the cmd line is still the standard => no?

**Comment by Yalz** [comment]
PR has been closed and both QA and issue maker were able to provide feedback
