### ISSUE TITLE
Instance http://localhost:8080/kbo/by-name?substring=& doesn't have a rdf:type tree:Node

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#776]
That is very specific bug, only occurs to the `tree:Node` `http://localhost:8080/kbo/by-name?substring=&`  for substring fragmentations.
I think it is an error when processing “&”。
This issue doesn't occur to other fragmented pages: e,g.

- http://localhost:8080/kbo/by-name?substring=v
- http://localhost:8080/kbo/by-name?substring=c

**Prerequitests:**

- LDES Server version: [ldes/ldes-server:1.1.0-SNAPSHOT](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#)
- LDES Server is up and running on the port 8080

**Scenario:**
1.  Post KBO event stream configuration to the server endpoint by 

```
    @prefix ldes: <https://w3id.org/ldes#> .  
    @prefix custom: <http://example.org/> .  
    @prefix dcterms: <http://purl.org/dc/terms/> .  
    @prefix tree: <https://w3id.org/tree#>.  
    @prefix sh: <http://www.w3.org/ns/shacl#> .  
    @prefix server: <http://localhost:8080/> .  
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .  
    @prefix kbo: <http://localhost:8080/kbo/> .  
    @prefix legal: <http://www.w3.org/ns/legal#> .  
    @base <http://localhost:8080> .  
      
    server:kbo a ldes:EventStream ;  
    ldes:timestampPath dcterms:issued;  
    ldes:versionOfPath dcterms:isVersionOf ;  
    custom:memberType legal:legalEntity;  
    tree:shape kbo:shape .  
      
    kbo:shape a sh:NodeShape ;  
    sh:nodeShape [  
    sh:closed true ;  
    sh:propertyShape []  
    ] ;  
    sh:deactivated true .
```
2. Post the [BEL 20 data](https://github.com/xdxxxdx/pyldes_kbo/tree/main/sample/bel20) to the LDES Server
3. Post substring fragmentation view by 

```
    @prefix ldes: <https://w3id.org/ldes#> .  
    @prefix custom: <http://example.org/> .  
    @prefix dcterms: <http://purl.org/dc/terms/> .  
    @prefix tree: <https://w3id.org/tree#>.  
    @prefix sh: <http://www.w3.org/ns/shacl#> .  
    @prefix server: <http://localhost:8080/> .  
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .  
    @prefix server: <http://localhost:8080/kbo/> .  
    @prefix legal: <http://www.w3.org/ns/legal#> .  
    @base <http://localhost:8080> .  
      
    </kbo/by-name> a tree:Node ;  
    tree:viewDescription [ a tree:ViewDescription ;  
    tree:fragmentationStrategy ([  
    a tree:SubstringFragmentation ;  
    tree:memberLimit "2"^^xsd:integer ;  
    tree:fragmentationPath legal:legalName ;  
    ]) ;  
    ] .
```

**Current result**
Brower to http://localhost:8080/kbo/by-name?substring=&, there is no triples indicating the current node is a `tree:Node`. e,g,
```
"
<http://localhost:8080/kbo/by-name?substring=&>
        rdf:type        tree:Node ;
        terms:isPartOf  <http://localhost:8080/kbo> .
"
```
But for any other fragmented pages e.g. <http://localhost:8080/kbo/by-name?substring=c>. it has
```
"
<http://localhost:8080/kbo/by-name?substring=c>
        rdf:type        tree:Node ;
        terms:isPartOf  <http://localhost:8080/kbo> .
 "
```

According to the Tree Spec:  [https://treecg.github.io/specification/#traversing](https://treecg.github.io/specification/#traversing)

> A  `tree:Relation`  MUST have one  `tree:node`  object of the type `tree:Node`.

As In the page http://localhost:8080/kbo/by-name?substring=
http://localhost:8080/kbo/by-name?substring=& is a ` tree:node` of a `tree:Relation`

```
       tree:relation   [ rdf:type    tree:SubstringRelation ;
                              tree:node   <http://localhost:8080/kbo/by-name?substring=&> ;
                              tree:path   legal:legalName ;
                              tree:value  "&"
                            ] ;
```
                           
There should be 

```
"
<http://localhost:8080/kbo/by-name?substring=&>
        rdf:type        tree:Node ;
        terms:isPartOf  <http://localhost:8080/kbo> .
"

```
In the whole RDF graph.
The turtle file with what is in the content when pinging http://localhost:8080/kbo/by-name?substring=& 
[substring_&.zip](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/11882433/substring_.zip)

**Comment by Yalz** [comment]
Hi @xdxxxdx ,

Could you provide a total data dump from your mongo? (Through whatever medium possible)
The issue seems to come from not escaping sensitive HTML characters. We'll investigate

**Comment by xdxxxdx** [comment]
Hello @Yalz , here is the full data dump :) 
[mongo_dump_776.zip](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/11892986/mongo_dump_776.zip)

**Comment by pj-cegeka** [comment]
This issue has been fixed. The problem was not escaping sensitive HTML characters in the url of fragments. These characters in the urls are now encoded.

**Comment by xdxxxdx** [comment]
Hello @WLefever-Cegeka ,
This issue occurs again on the version: [ldes/ldes-server:1.4.0-SNAPSHOT](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/776#)
The turtle file with what is in the content when pinging http://localhost:8080/kbo/by-name?substring=&
[substringbug.zip](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/12261153/substringbug.zip)
Thanks

**Comment by pj-cegeka** [comment]
Substring fragmentation has been deprecated so this issue with escaping sensitive HTML characters in the url of fragments can't happen anymore.

**Comment by xdxxxdx** [comment]
A great `done`
