### ISSUE TITLE
Add rdf:type tree:Collection to the output data stream

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#777]
Now our output stream is rdf:type to ldes:EventStream. e.g.

```
<http://localhost:8080/kbo>
        rdf:type            ldes:EventStream ;

```
I think the output stream, e.g.  `<http://localhost:8080/kbo>` should have a `rdf:type`  to the class `tree:Collection`. As the structure should conform to `tree:Collection.`

Please feel free to leave your comment.
Thanks

**Comment by xdxxxdx** [comment]
Hello @Yalz , here is the full data dump :) 
[mongo_dump_776.zip](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/11892986/mongo_dump_776.zip)

**Comment by sandervd** [comment]
As the eventstream is defined as a subclass of collection in the ontology, each instance of eventstream is automatically assumed to be an instance of collection.
I'd avoid adding the collection type, as it is already implied.

https://github.com/SEMICeu/LinkedDataEventStreams/blob/f9dc1463db5e3ca22caf9cfebc3e6d07b8b139e7/vocabulary.ttl#L33
