### ISSUE TITLE
Verify if the correct indexes are created when executing the Mongock Changesets

### ISSUE THREAD

**Issue by WLefever-Cegeka** [Informatievlaanderen/VSDS-LDESServer4J#778]
Verify if the correct indexes are created when executing the Mongock Changesets.
If this is not the case, fix :-)

**Comment by Tomvbe** [comment]
Isn't this something for the E2E repo?

**Comment by WLefever-Cegeka** [comment]
Verification can be done using the E2E or this repo, both are fine I think :-)

**Comment by Tomvbe** [comment]
I did a test with the mongock migrations and indices are created successfully when `spring.data.mongodb.auto-index-creation: true`. However I noticed the following issues:

- This property is not documented anywhere so a lot of people will miss this.
- Mongock does not delete indices when it removes a property. When removing an index, we probably want to cleanup the index as well.
