### ISSUE TITLE
ldes/ldes-server:1.1.0-SNAPSHOT: Time-based fragmentation doesn't conform the SPEC

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#791]
This case is used for keeping track of the discussion of the SPEC.

**Prerequisites:**
LDES Server version: [ldes/ldes-server:1.1.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldes-server/tags)

**Issue:**
Current [Deprecated time-based fragmentation implementation] doesn't conform to the MUST requirement :

**_When using relations such as tree:LessThanRelation or tree:GreaterThanRelation, the time literals need to be compared according to these 3 possible data types: xsd:date, xsd:dateTime or xsd:dateTimeStamp._**
https://treecg.github.io/specification/#time

Theoretically, the time-based fragmentation needs to be fragmented by the `tree:path`'s ontology's value.  (If there is a `tree:path` set).
With current deprecated implementation, the `tree:path` is not (always) a part of the LDES Member. So the validation cannot be done, and the conformance is not met.

**Comment by Yalz** [comment]
Closing ticket due to timebased fragmentation no longer being present
