### ISSUE TITLE
Document how to add multiple views at once via admin API

### ISSUE THREAD

**Issue by Tomvbe** [Informatievlaanderen/VSDS-LDESServer4J#793]
### Discussed in https://github.com/Informatievlaanderen/VSDS-LDESServer4J/discussions/729

<div type='discussions-op-text'>

<sup>Originally posted by **WLefever-Cegeka** June  2, 2023</sup>
This is currently not supported, but should be an easy extension.</div>

**Comment by xdxxxdx** [comment]
Hello @Tomvbe @Yalz , 
I am just wondering, is it documented somewhere at the end?
Thanks
