### ISSUE TITLE
Reference to a None Existing Repository

### ISSUE THREAD

**Issue by Krieke** [Informatievlaanderen/VSDS-LDESServer4J#81]
https://github.com/Informatievlaanderen/VSDS-LDESServer4J/blob/2bbd2bb92ff747ef7e2b0ae99b36077d9e4067ac/.env#L3

**Comment by WLefever-Cegeka** [comment]
Removed this in #93 . You can close the issue when documentation is updated.

**Comment by Krieke** [comment]
The issue was resolved in #93
