### ISSUE TITLE
ERROR 1 --- [nio-8080-exec-6] b.v.i.l.s.a.r.e.DefaultExceptionHandler  : null - Post LDES member to the server got 500 error

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#815]
**Prerequisites**
1. [ldes/ldes-server:1.2.0-SNAPSHOT](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#) is up 
2. KBO stream is configured on the LDES Server 
```
@prefix ldes: <https://w3id.org/ldes#> .
@prefix custom: <http://example.org/> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix tree: <https://w3id.org/tree#>.
@prefix sh:   <http://www.w3.org/ns/shacl#> .
@prefix server: <http://localhost:8080/> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
@prefix kbo: <http://localhost:8080/kbo/> .
@prefix legal: <http://www.w3.org/ns/legal#> .
@base <http://localhost:8080> .

server:kbo a ldes:EventStream ;
	ldes:timestampPath dcterms:issued;
	ldes:versionOfPath dcterms:isVersionOf ;
	custom:memberType legal:legalEntity;
	tree:shape kbo:shape .

kbo:shape a sh:NodeShape ;
	sh:nodeShape [
		sh:closed true ;
		sh:propertyShape []
		] ;
	sh:deactivated true .

```

**To Reproduce**
1.  Send [bel20](https://github.com/xdxxxdx/pyldes_kbo/tree/main/sample/bel20) data to the server endpoint  http://localhost:8080/kbo by curl command

**Current behavior**
Got 500 error for dataset: [0407.040.209.ttl](https://github.com/xdxxxdx/pyldes_kbo/blob/main/sample/bel20/0407.040.209.ttl)
<img width="678" alt="image" src="https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/b5c60f83-8f2f-4866-b1e0-6f9b317607e1">
In the server log:  I see `error: 2023-07-10 14:20:12 2023-07-10T12:20:12.238Z ERROR 1 --- [nio-8080-exec-2] .AdminRestResponseEntityExceptionHandler : null`
[2023-07-10.txt](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/12001853/2023-07-10.txt)
The most strange is this member is ingested to the server...

**Desktop (please complete the following information):**
 - OS: Windows 11 +WSL

**Comment by Yalz** [comment]
@xdxxxdx , very sorry for the very late message. 
The Content-Type should reflect your sent data. thus is should be text/turtle
