### ISSUE TITLE
Pagination fragmentation is broken

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-LDESServer4J#827]
When configuring a basic pagination, all members are returned in the first page.

**To Reproduce**
1. Run test 007: `npx cypress run -e tags="@test-007 and @ldio" -s "cypress/e2e/server.basics.feature"`
2. After the test fails, run: `curl "http://localhost:8080/connections/paged?pageNumber=1" -H "Accept: application/n-quads" > result.nq`
3. Check the number of members in the fragment: `cat result.nq | grep "https://w3id.org/tree#member" | wc -l`

**Expected behavior**
The first (and every subsequent immutable) fragment should contain a limited number of members (250 in this particular test).

**Comment by Yalz** [comment]
issue resolved as part of PR
