### ISSUE TITLE
Maybe it's an idea that every fragmentation strategy and every retention policy active in the server (so all the ones that are loaded) expose a shape and the validation of a view could then use these to verify if a valid view is being created.

### ISSUE THREAD

**Issue by sandervd** [Informatievlaanderen/VSDS-LDESServer4J#833]
### Discussed in https://github.com/Informatievlaanderen/VSDS-LDESServer4J/discussions/754
The domain module now includes validation rules for fragmentation strategies, the validation rules should be provided by the modules themselves.

**Comment by sandervd** [comment]
This is more an issue of abstraction in code, not really important unless we consider it important that 3th party fragmentation strategies can be added. Low prio for me.

**Comment by jobulcke** [comment]
Will be tackled in a different story
