### ISSUE TITLE
Split MemberProperties and viewReferences in Retention Module

### ISSUE THREAD

**Issue by WLefever-Cegeka** [Informatievlaanderen/VSDS-LDESServer4J#838]
In the first implementation of the Retention Module the entity `MemberProperties` contains Views (`private final List<String> viewReferences;`). However, it would be better to save these separately. Current implementation works, but is awkward, since there's a method `void saveMemberPropertiesWithoutViews(MemberProperties memberProperties);` which saves the MemberProperties, but not the viewReferences. This is needed since viewReferences are updated based on other events (and it's not guaranteed that they are later  in time than the creation of MemberProperties). Hence, the need for a split :-)

**Comment by Tomvbe** [comment]
We do not longer do different updates later on as of https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pull/1069
