### ISSUE TITLE
Substring fragmentation is not implemented in a case-sensitive way.  SubstringRelation 

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#840]
- LDES Server: [ldes/ldes-server:1.2.0-SNAPSHOT](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#)- 
- Substring fragmentation is configured on the server based on the http://www.w3.org/ns/legal#legalName

From the output graph [items_named.zip](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/12098085/items_named.zip), you could see the fragmentation based on the` relation: SubstringRelation` is not case sensitive 
e.g. 
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/397e3d18-b838-4f5f-9f13-158afade608a)

**Comment by WLefever-Cegeka** [comment]
HI @xdxxxdx,
For the substring fragmentation. As @rorlic indicated, we have based our algorithm on the implementation in TREEcg.
I added the reference @rorlic referred to in the docs.
Could we close this issue?
If there's a need by a user of the LDES Server to have a case-sensitive implementation, they could very easily load another implementation in the server.

**Comment by sandervd** [comment]
To be completely honest, I would remove support for substring fragmentation.

Let me explain why:
- The intent of the LDES server is data replication, to transfer changes in state from one system to another.
This means that to be able to able to answer a query, you need to materialize the latest state 'somewhere', you need to parse all pages of a certain partition (a partition in case of a substring would be token the user is querying).
- Large number of partitions a member is assigned to: depending on the applied tokenizer, say, you want matches of mid word tokens (match 'chip' when the string contained 'microchips')
- Search is a balance of complex tradeoffs the server can't make: tokenization, stemming rules (which are language dependent) , stopword filters,... a server configured partitioning will never be able to make the right decision for all consumers.
- LDES isn't a query api; an application needs a materialized dataset anyway to work. It's then a matter of indexing the required strings in a lucene index during ingest, using the rules that are appropriate for the use case.
- It doesn't work anyway: as LDES has no delete semantics, changing a string leaves it in the wrong partition to be found.
For example:
State at t0:
<object> rdfs:label "Kat"
Turned into version object:
<v1> isVersionOf <object>
-> gets partition key 'K.a.t'
State at t1:
<object> rdfs:label "Hond"
Turned into version object:
<v2> isVersionOf <object>
-> gets partition key 'H.o.n.d'
Searching for 'Kat' will still return the 'old' state of the object.
This will lead to outdated information to be returned. At the moment there is no way to fix this, as there is no way defined on how to communicate deletes.
(only time based fragmentation is in fact reliable at the moment)

If it was only up to me, I would suggest to either remove this feature from the server altogether.
As this will probably cause some controversy, I would for now turn it into a feature flag that turns on experimental components.
If we then want to improve the quality of the experimental features, we can do so, but I don't see this as a very important thing.

**Comment by WLefever-Cegeka** [comment]
In the meantime I updated the substring fragmentation so that you can configure it to work case-sensitive or case-insensitive.
https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pull/859

**Comment by xdxxxdx** [comment]
Validated on the snapshot version 1.4.0
