### ISSUE TITLE
Fragmentations broken:  Sensitive HTML characters are not encoded in a proper way, got broken entity url e.g. <http://localhost:8080/kbo/by-location?tile=15%2F16887%2F11019>  

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#844]
**Describe the bug**
1.LDES Server version: [ldes/ldes-server:1.3.0-SNAPSHOT](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#)
2. time-based, String based, Geospatial fragmentation are configured to the server
3. KBO data set of BEL 20 data are posted to the server.

**To Reproduce**
1. Go to any time fragmented page:  e.g. http://localhost:8080/kbo/by-time?created=2023-07-20T15:41:43.215Z

**Current behavior**
Got wrong coded characters: <http://localhost:8080/kbo/by-time?created=2023-07-20T15%3A41%3A43.215Z> which leads to broken stream
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/2b2418c8-72f4-4e7e-b34b-789289026fb7)

Also impact by location: 
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/0a7b6c09-73dc-4ed0-bd2e-f54e391133e0)

**Expected behavior**
The entity of the example should stay <http://localhost:8080/kbo/by-time?created=2023-07-20T15:41:43.215Z>

**Desktop (please complete the following information):**
 - OS: Windows 11 +WSL

**Comment by WLefever-Cegeka** [comment]
Should be fixed with PR merge #850

**Comment by xdxxxdx** [comment]
Wait for the refix of : https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/776
