### ISSUE TITLE
After upgrading LDES Server, the old ingested LDES members' fragmentations are not reachable by the endpoint

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#855]
**Prerequsites**

- [ldes/ldes-server:1.3.0-SNAPSHOT](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#)
- E2E working repo for Sprint 31:  8b116de5e53f392fc2342f9fc3f054400cabd3c4
- Test directory: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/tests/021.server-upgrade
- Old LDES Server: LDES_OLD_SERVER_TAG:-20230405T0843 is up and running
- 30 LDES members are ingested to the LDES Server
- 2 LDES Fragmentation are created for the 30 LDES Members

**To Reproduce**
1.  Pause the workbench output. `curl -X POST "http://localhost:8081/admin/api/v1/pipeline/halt"`
3.  Bring old server down (stop it, remove volumes and image without confirmation). `docker compose rm --stop --force --volumes old-ldes-server`
4.  Launch new server, wait until database migrated and server started `docker compose up new-ldes-server -d
docker logs --tail 1000 -f $(docker ps -q --filter "name=new-ldes-server$")`
5.  Resume the workbench output. `curl -X POST "http://localhost:8081/admin/api/v1/pipeline/resume"`

**Current behavior**
**308 NEW LDES members are ingested to the new LDES Server, together with the OLD 30 LDES members. => 338 LDES members are in the ` iow_devices.ingest_ldesmember` table**
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/d5d2cfab-afe8-443b-a5e4-9b459b254b71)
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/297e1fea-8cac-4036-86fc-575c385c90f6)
DB dump for the mentioned two tables: 
[iow_devices.ldesmember.zip](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/12171832/iow_devices.ldesmember.zip)

**13 new fragmentations are created in the table iow_devices.fragmentation_fragment which covers 12*25+8 = 308 LDES Member.**

![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/35ea7aa3-4b99-4c38-ad81-ad644c5ba946)
DB dump: [iow_devices.fragmentation_fragment.zip](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/12171844/iow_devices.fragmentation_fragment.zip)

**_In current situation, the 30 LDES ingested members are only fragmented in the OLD LDES Server, but their fragmentations are not reachable by the endpoint._**

![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/2fa71ef5-2e84-4bfa-a955-98fb36c1a588)
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/20d4d2fe-70b8-4188-afb1-541acbe5fdb2)

[iow_devices.ldesfragment.zip](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/12171878/iow_devices.ldesfragment.zip)
[iow_devices.fragmentation_allocation.zip](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/12171879/iow_devices.fragmentation_allocation.zip)

**Expected behavior**
The 30 LDES Members (migrated from the old LDES Server) should be still findable by the fragmentation endpoint.

**Comment by Tomvbe** [comment]
Hi @xdxxxdx there was indeed a bug in de mongock migration that we resolved last week. I cherry picked this to the 1.3.0-SNAPSHOT with commit https://github.com/Informatievlaanderen/VSDS-LDESServer4J/commit/318ec24b99e2a08e23da0ca7e13a65ef1a658ca5. In about an hour, the new 1.3.0-SNAPSHOT image should be online, can you retest the issue with the hotfix?

**Comment by xdxxxdx** [comment]
Validated on the [ldes/ldes-server:1.4.0-SNAPSHOT](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/855#)
