### ISSUE TITLE
Add API document for the newly implemented : ldes-fragmentisers-timebased-hierarchical

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#868]
LDES Server version: [ldes/ldes-server:1.4.0-SNAPSHOT](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=#)
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/2a862c51-7edd-4049-bfab-827fa41ad08a)

As you could see, there is no example  for the new implemented ldes-fragmentisers-timebased-hierarchical in /admin/api/v1/eventstreams/{collectionName}/views,  please add one accordingly. Thanks

**Comment by Tomvbe** [comment]
Fixed in https://github.com/Informatievlaanderen/VSDS-LDESServer4J/pull/1048/files#diff-4a07f0436aba77e9104afd75b78a80ba81f209d9b53062927cf9501c88bbee4b
