### ISSUE TITLE
After upgrading LDES Server, new ingested LDES member restarts the sequence from 1

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#875]
**Prerequisites**

- [ldes/ldes-server:1.4.0-SNAPSHOT](https://hub.docker.com/r/ldes/ldes-server/tags#)
- Test directory: https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/tests/021.server-upgrade
- Old LDES Server: LDES_OLD_SERVER_TAG:-20230405T0843 is up and running
- 314 LDES members are ingested to the LDES Server

**To Reproduce**
1.  Pause the workbench output. `curl -X POST "http://localhost:8081/admin/api/v1/pipeline/halt"`
3.  Bring old server down (stop it, remove volumes and image without confirmation). `docker compose rm --stop --force --volumes old-ldes-server`
4.  Launch new server, wait until database migrated and server started `docker compose up new-ldes-server -d
docker logs --tail 1000 -f $(docker ps -q --filter "name=new-ldes-server$")`
5.  Resume the workbench output. `curl -X POST "http://localhost:8081/admin/api/v1/pipeline/resume"`

**Current behavior**
**851 NEW LDES members are ingested to the new LDES Server, together with the OLD 315 LDES members. => 1165 LDES members are in the ` iow_devices.ingest_ldesmember` table**
**The end of the `sequenceNr` is 851 instead of 1165**
![image](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/assets/15314807/7758ab16-c71a-4661-abe4-9951fde4b41b)

**The `sequenceNr` is restarted from 1 from the new ingest members of the new LDES Server**
![image](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/assets/15314807/97d50c65-15e2-480e-bf0f-e1aac13881b1)

Table dump:  [iow_devices.ingest_ldesmember.zip](https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/files/12273764/iow_devices.ingest_ldesmember.zip)

**Expected behavior**
All 1165 ldes members should be in a continuously sequence?. e.g. from 1 to 1165

**Comment by Yalz** [comment]
Hi @xdxxxdx ,
Although this issue is still there, the reality is that this has very little impact on current customers.
Everyone who used a ldes-server older than ~june 2023 might have this behaviour. 
But the worst thing that could come of this, is that a few members are fragmented out of order. 

However since we don't have any more onboarders who haven't migrated yet. This is to be a non issue
