### ISSUE TITLE
Performance issues with retention

### ISSUE THREAD

**Issue by pj-cegeka** [Informatievlaanderen/VSDS-LDESServer4J#883]
While ingesting a larger amount of members while having a retention policy set, the deletion of members cannot keep up with the amount of ingested members. This could cause problems when the db fills up.
The retention seemingly slows down a lot when the number of members increases.

**Comment by Tomvbe** [comment]
Related to this are the performance issues we have when deleting a collection or view with a lot of members. The bottleneck in these actions is within the retention module.

**Comment by Tomvbe** [comment]
When fixing this issue, it could be interesting to include this in a test plan in the performance testing repo
