### ISSUE TITLE
Reduce the amount of logging / fix startup warnings

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-LDESServer4J#896]
Please fix the cause of the warnings during startup and/or reduce the amount of logging.

**Comment by jeflaenen** [comment]
Add an option to only show errors and hide warnings

**Comment by Tomvbe** [comment]
> Add an option to only show errors and hide warnings

This is already possible by adding the following config to the 'application.yml' 

```
logging:
  level:
    root: ERROR
```
