### ISSUE TITLE
ldes/ldes-server:2.0.1-SNAPSHOT Substring Fragmented broken. (Hierarchical layer created, but only  ` substring=& `)

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#903]
**Describe the bug**
Hierarchical fragmentation is applied on the substring fragmentation.
But for now, only ` substring=& `can be created at the middle layer of the fragmentation (before pagination layer).
Fragmentations  like  ` substring=a `,  ` substring=b ` are never created.

**To Reproduce**
1. Follow the step by step guide https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/tree/main/tests/006.server-substring-fragment-ldes
2. Add `tree:memberLimit  "10"^^xsd:integer ;` to https://github.com/xdxxxdx/VSDS-LDES-E2E-testing/blob/main/tests/006.server-substring-fragment-ldes/config/addresses.by-name.ttl. For avoiding SHACL complain
3. Wait for 696 LDES members ingested

**Current behavior**
A fragmentation as followed is created:
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/9fb29b3d-d971-41c7-9e20-355cbad9b02a)

**_The middle layer is
**http://localhost:8080/addresses/by-name?substring=**. And this layer is not extensible, which means I don't see possibilities that it can be  http://localhost:8080/addresses/by-name?substring=a, http://localhost:8080/addresses/by-name?substring=b etc.. 
as the original ides of substring fragmentation._**
**Also I think, Semantic string related `tree:Relation`s e.g. tree:SubstringRelation etc.. should continuously be applied.** 

DB dump: 
[grar.ingest_ldesmember.zip](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/12513592/grar.ingest_ldesmember.zip)

**Expected behavior**
Hierarchical substring fragmentation happens properly.

**Comment by xdxxxdx** [comment]
Substring fragmentation is going to be removed: https://vlaamseoverheid.atlassian.net/wiki/spaces/VSDSPUB/pages/6435536897/2023-09-14+Weekly+Design+Session

**Comment by jeflaenen** [comment]
Removal of substring fragmentation will be taken up in https://vlaamseoverheid.atlassian.net/browse/VSDSPUB-928
