### ISSUE TITLE
PaginationFragmentation also becomes hierarchical. Fragmentations as http://localhost:8080/kbo/by-pages?pageNumber=1&pageNumber=1 created

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#905]
[ldes/ldes-server: 2.0.1-SNAPSHOT](https://hub.docker.com/r/ldes/ldes-server/tags)

**Describe the bug**
`tree:PaginationFragmentation` also sets the fragmentation to a hierarchical way. 

**To Reproduce**
1. Start LDES Server
2. Set KBO stream by:
```
@prefix ldes: <https://w3id.org/ldes#> .
@prefix custom: <http://example.org/> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix tree: <https://w3id.org/tree#>.
@prefix sh:   <http://www.w3.org/ns/shacl#> .
@prefix server: <http://localhost:8080/> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
@prefix kbo: <http://localhost:8080/kbo/> .
@prefix legal: <http://www.w3.org/ns/legal#> .
@base <http://localhost:8080> .

server:kbo a ldes:EventStream ;
	ldes:timestampPath dcterms:issued;
	ldes:versionOfPath dcterms:isVersionOf ;
	tree:shape kbo:shape .

kbo:shape a sh:NodeShape ;
	sh:targetClass legal:legalEntity .
```
3. Set `by-pages` fragmentation by:
```
@prefix ldes: <https://w3id.org/ldes#> .
@prefix custom: <http://example.org/> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix tree: <https://w3id.org/tree#>.
@prefix sh:   <http://www.w3.org/ns/shacl#> .
@prefix server: <http://localhost:8080/> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
@prefix server: <http://localhost:8080/kbo/> .
@prefix legal: <http://www.w3.org/ns/legal#> .
@base <http://localhost:8080> .

</kbo/by-pages> a tree:Node ;
  tree:viewDescription [ a tree:ViewDescription ;
    tree:fragmentationStrategy ([
		a tree:PaginationFragmentation ;
		tree:memberLimit "2"^^xsd:integer ;
	]) ;
		  tree:pageSize "5"^^xsd:integer ;
] .
```
4. Ingest 20 ldes members

**Current result**
We got fragmentation like 
http://localhost:8080/kbo/by-pages?pageNumber=1&pageNumber=1
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/e31596fb-2bd9-4672-8041-9f960a8c2fa8)
DB Dump: [ldes.fragmentation_fragment.zip](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/12524505/ldes.fragmentation_fragment.zip)
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/662f3f97-2d22-46b5-8980-80a8443e9e4d)

**http://localhost:8080/kbo/by-pages?pageNumber=1&pageNumber=1 doesn't link to the LDES members**
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/01f1222b-d18c-4ad6-8229-282969910f35)

**Expected result:**
From my perspective, the pagination fragmentation should not be hierachical.

**Comment by Yalz** [comment]
see #909 for further progress
