### ISSUE TITLE
Continuously compacting is not working,  numberOfMembers doesn't reflect the correct number inside the fragmentation.

### ISSUE THREAD

**Issue by xdxxxdx** [Informatievlaanderen/VSDS-LDESServer4J#906]
ldes/ldes-server:2.0.1-SNAPSHOT

**Describe the bug**
Continuously compacting is not working,  `numberOfMembers` doesn't reflect the correct number inside the fragmentation.

**To Reproduce**
1. Start LDES Server
2. Set KBO stream by:
```
@prefix ldes: <https://w3id.org/ldes#> .
@prefix custom: <http://example.org/> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix tree: <https://w3id.org/tree#>.
@prefix sh:   <http://www.w3.org/ns/shacl#> .
@prefix server: <http://localhost:8080/> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
@prefix kbo: <http://localhost:8080/kbo/> .
@prefix legal: <http://www.w3.org/ns/legal#> .
@base <http://localhost:8080> .

server:kbo a ldes:EventStream ;
	ldes:timestampPath dcterms:issued;
	ldes:versionOfPath dcterms:isVersionOf ;
	tree:shape kbo:shape .

kbo:shape a sh:NodeShape ;
	sh:targetClass legal:legalEntity .
```
3. set up pagination3 view by:
```
@prefix ldes: <https://w3id.org/ldes#> .
@prefix tree: <https://w3id.org/tree#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix server: <http://localhost:8080/mobility-hindrances/> .

server:pagination3 tree:viewDescription [
    tree:fragmentationStrategy  () ;
    tree:pageSize "3"^^<http://www.w3.org/2001/XMLSchema#int> ;
    ldes:retentionPolicy [
        a ldes:LatestVersionSubset;
        ldes:amount 1 ;
    ] ;
] .
```

4. Ingest Bel 20 datasets. Three times different versions. 
5. Delete the by-page default view.

**Current behavior**
All DB Dump: [ldes.fetch_allocation.zip](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/files/12525136/ldes.fetch_allocation.zip)

With the retention policy, only one-version BEL20 KBO dataset will always be kept. 
In the `ldes.fetch_allocation` table, we can see All remaining kbo members are linked to fragments `/kbo/pagination3?pageNumber=27 to /kbo/pagination3?pageNumber=34 `.
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/d69e49b5-7cad-4686-998f-a5d6897b3035)

In the ldes.fragmentation_fragmen table:
**1. Some fragements have no member linked to it but the `numberOfMembers` is not 0**
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/878437d0-49f2-409f-bca6-95c41231fce9)
2. Some Not gonna be deleted fragments have no member linked to it (or less than pageSize). but no further compaction on it.
![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/8839ef34-b00c-46f2-8667-74dcaefb10f4)

The LDES Server provides a fragmentation showed as follow diagram:

![image](https://github.com/Informatievlaanderen/VSDS-LDESServer4J/assets/15314807/594fcee8-4fb2-4b5c-a98b-9b04131e764d)
There are large parts of fragmentations are empty.

**Expected result:**
 `numberOfMembers` should reflect how many members are in the fragmentation correctly?
The empty fragmentations should be continuously compacted?

**Comment by WLefever-Cegeka** [comment]
Hi @xdxxxdx ,
Thanks for mentioning this. `numberOfMembers` is a poorly chosen variable name in this case and originates from earlier versions of the server. This variable actually keeps track of how many members have been assigned to a fragment. It does not take into account retention, so it will never decrease. I'll add a ticket on our backlog.

**Comment by xdxxxdx** [comment]
changed from numberOfMembers to nrOfMemebersAdded, which reflects how many members were added to this fragmentation before.
