### ISSUE TITLE
Remove 'paginination fragmentation' as it is always set

### ISSUE THREAD

**Issue by sandervd** [Informatievlaanderen/VSDS-LDESServer4J#909]
**Is your feature request related to a problem? Please describe.**
Pagination is always set, an is managed automatically. Users shouldn't be able to configure it as a partitioning strategy.

**Describe the solution you'd like**
Delete it a partitioning strategy.

**Comment by jeflaenen** [comment]
https://vlaamseoverheid.atlassian.net/browse/VSDSPUB-1050 is logged for this, this issue can be closed.
