### ISSUE TITLE
Provide a docker-compose file with tracing enabled

### ISSUE THREAD

**Issue by sandervd** [Informatievlaanderen/VSDS-LDESServer4J#929]
There are only vague mentions of how tracing should be configured in the documentation, but no working example.

**Comment by Yalz** [comment]
Although I understand your point.. How far do you want to go in this? 
Provide the tracing configuration for LDES Server? also include a Jaeger instance? Also include a full Grafana solution?
To me it's a bit of a slippery slope how far we want to support this

**Comment by Yalz** [comment]
To be replaced with LDES Server Docs as part of Monitoring & logging stories
