### ISSUE TITLE
Hierarchical time-based fragmentation uses illegal tree:value literals in the tree:relations

### ISSUE THREAD

**Issue by rorlic** [Informatievlaanderen/VSDS-LDESServer4J#945]
The tree:value literals in a hierarchical time-based fragment are invalid values. E.g.
```
tree:value  "2023"^^<http://www.w3.org/2001/XMLSchema#dateTime>
```
is not a valid xsd:dateTime. It is not even a legal xsd:date.

**Steps to reproduce**
* go to https://www.liquid-technologies.com/online-xsd-validator
* paste the following schema: `<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema"><xs:element name = "value" type = "xs:dateTime"/></xs:schema>`
* paste a value to validate, e.g. `<value>2023</value>`
* hit validate
* notice that the validator shows an error

**Note** that this issue is true for most intermediate fragment nodes

**Comment by Tomvbe** [comment]
A valid dateTime looks like: 2023-10-19T15:30:00Z
A valid date looks like: 2023-10-19

If the value should only be 2023, we probably just want to use another type
