### ISSUE TITLE
Optimise Ldes Member Ingestion

### ISSUE THREAD

**Issue by Yalz** [Informatievlaanderen/VSDS-LDESServer4J#998]
**Describe the problem**
As part of performance optimisation, we noticed that the member ingestion algorithm performs two db queries per ingestion:
* verifies if member exists
* save member

This should be replaced with a single upsert query which can return a boolean wether the member was saved.

**Comment by rorlic** [comment]
Be careful not to overwrite an existing member.

**Comment by sandervd** [comment]
We don't need this, we need to create version objects in the server :trollface:
